/*
 * SPDX-FileCopyrightText: 2026 overpolish
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 */

#pragma once

#import <Foundation/Foundation.h>
#import <simd/simd.h>

typedef enum : uint32_t {
  KKBezierPointLinear = 0,
  KKBezierPointBezier = 1,
} KKBezierPointType;

typedef struct {
  float x, y;
  float inX, inY;
  float outX, outY;
  uint32_t type;
} KKBezierPoint;

#define kSketchRoughnessDefault 1.0f
#define kSketchBowingDefault 1.0f
#define kSketchStrokesDefault 2
#define kSketchFillGapDefault 25.0f
#define kSketchFillAngleDefault -41.0f
#define kSketchFillWeightDefault 3.0f

NS_ASSUME_NONNULL_BEGIN

@interface KKBezierPath : NSObject

/// Number of points.
@property(nonatomic, readonly) NSUInteger count;

/// Number of path segments (count + 1 for MagicMove, count for closed paths).
@property(nonatomic, readonly) NSUInteger segmentCount;

/// Whether the path forms a closed loop (last point connects to first).
@property(nonatomic, assign) BOOL closed;

/// Whether the path was created as a rectangle (enables corner radius handles).
@property(nonatomic, assign) BOOL isRect;

/// Whether the path was created with the line tool.
@property(nonatomic, assign) BOOL isLine;

/// Whether the path is hidden in the canvas.
@property(nonatomic, assign) BOOL hidden;

/// Whether the path is locked (visible but non-interactive).
@property(nonatomic, assign) BOOL locked;

/// Whether this layer is a raster image (rendered as a textured quad).
@property(nonatomic, assign) BOOL isImage;

/// Absolute file path to the source image (PNG, JPEG, etc.).
/// Only meaningful when isImage == YES.
@property(nonatomic, copy, nullable) NSString *imagePath;

/// Original image aspect ratio (width / height). Set at import time.
/// Only meaningful when isImage == YES.
@property(nonatomic, assign) float imageAspect;

/// Whether this entry is a group (contains no points, acts as a folder).
@property(nonatomic, assign) BOOL isGroup;

/// Unique identifier for this group (set on group entries only).
@property(nonatomic, copy, nullable) NSString *groupID;

/// The groupID of this item's parent group, or nil if top-level.
@property(nonatomic, copy, nullable) NSString *parentGroupID;

/// Display name for the layer list.
@property(nonatomic, copy, nullable) NSString *name;

/// Stable per-layer UUID, autogenerated at init. Used as the timing-lane
/// `groupKey` so timing data follows the layer across rename/reorder.
/// Persists in `dataRepresentation` (v17+); older blobs get a fresh UUID
/// on load.
@property(nonatomic, copy) NSString *layerID;

/// Per-corner radius fractions 0–1 (TL, TR, BR, BL). 0 = sharp, 1 = max.
@property(nonatomic, assign) float cornerRadiusTL;
@property(nonatomic, assign) float cornerRadiusTR;
@property(nonatomic, assign) float cornerRadiusBR;
@property(nonatomic, assign) float cornerRadiusBL;

/// Whether this path renders a stroke (default YES).
@property(nonatomic, assign) BOOL strokeEnabled;

/// Stroke color mode (0=solid, 1=gradient). Default 0.
@property(nonatomic, assign) uint8_t strokeColorMode;

/// Stroke gradient type (0=radial, 1=linear). Matches Glow's ordering.
@property(nonatomic, assign) uint8_t strokeGradientType;

/// Stroke gradient angle in degrees (default 0).
@property(nonatomic, assign) float strokeGradientAngle;

/// Stroke gradient stops as JSON (KKGradientStop array). Empty when solid.
@property(nonatomic, copy, nullable) NSString *strokeGradientJSON;

/// Stroke width at the start of this path (default 8.0).
@property(nonatomic, assign) float strokeWidth;

/// Stroke width at the end of this path. When different from strokeWidth,
/// the stroke tapers linearly along the path. Only meaningful for open paths.
/// Default 0 means "use strokeWidth" (no taper).
@property(nonatomic, assign) float endWidth;

/// Stroke color components (default red: 1, 0, 0).
@property(nonatomic, assign) float strokeR;
@property(nonatomic, assign) float strokeG;
@property(nonatomic, assign) float strokeB;

/// Object opacity 0–1 (default 1.0). Multiplied into stroke and fill alpha.
@property(nonatomic, assign) float opacity;

/// Line cap style for open paths (0=butt, 1=round, 2=square). Default 0.
@property(nonatomic, assign) uint8_t lineCap;

/// Line join style (0=miter, 1=round, 2=bevel). Default 0.
@property(nonatomic, assign) uint8_t lineJoin;

/// Stroke style (0=solid, 1=dashed, 2=dotted). Default 0.
@property(nonatomic, assign) uint8_t strokeStyle;

/// Dash length in points (default 20.0). Only used when strokeStyle == 1.
@property(nonatomic, assign) float dashLength;

/// Dash gap in points (default 10.0). Only used when strokeStyle == 1.
@property(nonatomic, assign) float dashGap;

/// Dot gap in points (default 10.0). Only used when strokeStyle == 2.
@property(nonatomic, assign) float dotGap;

/// Start marker type (0=none, 1=arrow, 2=circle, 3=square). Default 0.
@property(nonatomic, assign) uint8_t startMarker;

/// End marker type (0=none, 1=arrow, 2=circle, 3=square). Default 0.
@property(nonatomic, assign) uint8_t endMarker;

/// Start marker size as percentage of stroke width (default 300).
@property(nonatomic, assign) float startMarkerSize;

/// End marker size as percentage of stroke width (default 300).
@property(nonatomic, assign) float endMarkerSize;

/// Whether this path uses sketch (hand-drawn) rendering (default NO).
@property(nonatomic, assign) BOOL sketchEnabled;

/// Sketch roughness 0–3 (default 1.0). Higher = more jitter.
@property(nonatomic, assign) float sketchRoughness;

/// Sketch bowing 0–3 (default 1.0). Higher = more line curvature.
@property(nonatomic, assign) float sketchBowing;

/// Number of sketch stroke passes (1 = single, 2 = double/overlay). Default 2.
@property(nonatomic, assign) uint8_t sketchStrokes;

/// Sketch fill style (0=solid, 1=hachure, 2=cross-hatch, 3=zigzag, 4=dots).
/// Default 0 (solid). Only meaningful when sketchEnabled && fillEnabled.
@property(nonatomic, assign) uint8_t sketchFillStyle;

/// Gap between hachure lines in points (default 25). Larger = more spaced.
@property(nonatomic, assign) float sketchFillGap;

/// Angle of hachure lines in degrees (default -41, matching Rough.js).
@property(nonatomic, assign) float sketchFillAngle;

/// Stroke weight of hachure fill lines in points (default 3).
@property(nonatomic, assign) float sketchFillWeight;

/// Random seed for deterministic sketch rendering. Generated once when
/// sketch is enabled, then stored so the jitter stays stable.
@property(nonatomic, assign) uint32_t sketchSeed;

/// Number of contours (1 for simple paths, >1 for compound paths like SVG
/// paths with multiple M...Z sequences). Each contour is independently closed.
@property(nonatomic, readonly) NSUInteger contourCount;

/// Returns the point index range for the given contour.
- (NSRange)contourRangeAtIndex:(NSUInteger)contourIndex;

/// Mark the start of a new contour at the current point count.
/// Called by the SVG parser when encountering a new M after Z.
- (void)beginContour;

/// Split this compound path into separate closed paths for stroke rendering.
/// Returns nil if the path has only one contour.
- (nullable NSArray<KKBezierPath *> *)splitContours;

/// Whether this path has a solid fill (default NO).
@property(nonatomic, assign) BOOL fillEnabled;

/// Fill color components (default white: 1, 1, 1).
@property(nonatomic, assign) float fillR;
@property(nonatomic, assign) float fillG;
@property(nonatomic, assign) float fillB;

/// Fill tint amount for image layers (0–1, default 1.0).
/// 0 = original image, 1 = fully colorized by fill color.
@property(nonatomic, assign) float fillTint;

/// Fill color mode (0=solid, 1=gradient). Default 0.
@property(nonatomic, assign) uint8_t fillColorMode;

/// Fill gradient type (0=radial, 1=linear). Matches Glow's ordering.
@property(nonatomic, assign) uint8_t fillGradientType;

/// Fill gradient angle in degrees (default 0).
@property(nonatomic, assign) float fillGradientAngle;

/// Fill gradient stops as JSON (KKGradientStop array). Empty when solid.
@property(nonatomic, copy, nullable) NSString *fillGradientJSON;

+ (instancetype)pathWithData:(nullable NSData *)data;
- (NSData *)dataRepresentation;

+ (NSMutableArray<KKBezierPath *> *)pathsFromBlob:(nullable NSData *)blob;
+ (NSData *)blobFromPaths:(NSArray<KKBezierPath *> *)paths;

- (KKBezierPoint)pointAtIndex:(NSUInteger)index;

- (void)insertAtIndex:(NSUInteger)index position:(simd_float2)pos;
- (void)removeAtIndex:(NSUInteger)index;
- (void)moveAtIndex:(NSUInteger)index to:(simd_float2)pos;
- (void)setInHandle:(simd_float2)offset atIndex:(NSUInteger)index;
- (void)setOutHandle:(simd_float2)offset atIndex:(NSUInteger)index;
- (void)setType:(KKBezierPointType)type atIndex:(NSUInteger)index;
- (void)translateBy:(simd_float2)delta;

/// Rebuild this path as a rounded rectangle with per-corner fractions.
/// Each fraction 0–1: 0 = sharp, 1 = max radius for that corner.
- (void)setRoundedRectWithMin:(simd_float2)min
                          max:(simd_float2)max
                   fractionTL:(float)tl
                   fractionTR:(float)tr
                   fractionBR:(float)br
                   fractionBL:(float)bl
                  canvasWidth:(float)canvasW
                 canvasHeight:(float)canvasH;
- (void)toggleTypeAtIndex:(NSUInteger)index
                    start:(simd_float2)start
                      end:(simd_float2)end;

/// Evaluate a single path segment at local t (0-1).
/// start/end are the anchor points for MagicMove-style relative paths.
- (simd_float2)evaluateSegment:(NSUInteger)segIndex
                           atT:(float)t
                         start:(simd_float2)start
                           end:(simd_float2)end;

/// Evaluate the cubic bezier between point at index and index+1 at t (0-1).
/// Uses absolute coordinates (no start/end anchors).
- (simd_float2)evaluatePointAtIndex:(NSUInteger)index
                          nextIndex:(NSUInteger)nextIndex
                                atT:(float)t;

/// Evaluate the tangent between point at index and index+1 at t (0-1).
- (simd_float2)evaluateTangentAtIndex:(NSUInteger)index
                            nextIndex:(NSUInteger)nextIndex
                                  atT:(float)t;

/// Arc-length parameterized position along the full path at global t (0-1).
- (simd_float2)positionAtT:(float)t
                     start:(simd_float2)start
                       end:(simd_float2)end;

@end

NS_ASSUME_NONNULL_END
