/*
 * SPDX-FileCopyrightText: 2026 overpolish
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 */

#import "MirageCustomShader.h"

#import "Constants.h" // declares MirageCustomDefaultShaderSource

// The two baked GLSL sources. Both are trivial image-shader bodies, so they
// always transpile - which is the point: they are the fallbacks every other
// path leans on when the user's own source is absent or broken.

// The default shader: the classic cosine-palette plasma, so Custom renders
// something alive out of the box (and seeds the editor). It also ships the two
// directive-driven on-screen controls the timing guide teaches on - a Center
// the pattern radiates from (a point handle) and a Scale (a ring around that
// centre) - so a fresh instance has real OSCs, not just code. Default values
// reproduce the plain plasma: Center at the frame middle, Scale 3.
//
// Doubles as the worked example for the directive syntax, so it deliberately
// shows both `group=` forms and one opt-in built-in. Keep it that way when
// touching it.
NSString *MirageCustomDefaultShaderSource(void) {
  return @"// SPDX-FileCopyrightText: 2026 overpolish\n"
         @"// SPDX-License-Identifier: MIT\n"
         @"\n"
         @"// #template generator\n"
         @"\n"
         @"// The built-in Speed lane, which scales iTime. It annotates no "
         @"uniform because\n"
         @"// it drives one the plugin already gives every shader. Opt-in, as "
         @"the seed and\n"
         @"// grain built-ins are - leave it out and the shader just runs at "
         @"speed 1. No\n"
         @"// group= here, so it lands in the default group.\n"
         @"// #speed\n"
         @"\n"
         @"// The long form of group=: name plus the SF Symbol the group "
         @"header draws.\n"
         @"// #point label=\"Center\" group={\"Pattern\", "
         @"\"circle.hexagongrid\"} osc default=\"0.5,0.5\"\n"
         @"uniform vec2 uCenter;\n"
         @"\n"
         @"// The short form: the group already has its icon from the first "
         @"control that\n"
         @"// named one, so this just joins it.\n"
         @"// #percent label=\"Scale\" group=\"Pattern\" osc=ring link=uCenter "
         @"min=25 max=400 default=100\n"
         @"uniform float uScale;\n"
         @"\n"
         @"// Cycles across the frame at 100%. Scale DIVIDES this, so the lane "
         @"reads as a\n"
         @"// zoom: turn it up and the pattern gets bigger. Multiplying would "
         @"make it a\n"
         @"// frequency instead, where raising it packs in more repetitions "
         @"and the picture\n"
         @"// appears to pull away - which is the wrong way round for "
         @"something called\n"
         @"// Scale.\n"
         @"const float kBaseFrequency = 3.0;\n"
         @"\n"
         @"void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
         @"{\n"
         @"\tvec2 uv = (fragCoord - uCenter) / iResolution.xy;\n"
         @"\tfloat freq = kBaseFrequency / max(uScale, 0.001);\n"
         @"\tvec3 col = 0.5 + 0.5 * cos(iTime + uv.xyx * freq + vec3(0.0, 2.0, "
         @"4.0));\n"
         @"\tfragColor = vec4(col, 1.0);\n"
         @"}\n";
}

// The built-in technical transform. Camera curves and gamut matrices are
// transcribed from the ASWF OpenColorIO ACES configuration v4.0 CLFs, except
// Fujifilm F-Log / F-Log2 and Nikon N-Log, which that config does not carry.
// Display curves are the published standards (sRGB, BT.1886, BT.2100 HLG,
// SMPTE ST 2084). We keep the transform in shader source (rather than a private
// render branch) so it inherits the normal browser, timeline, preview,
// persistence and stacking behaviour.
NSString *MirageColorTransformShaderSource(void) {
  return @"// SPDX-FileCopyrightText: 2026 overpolish\n"
         @"// SPDX-License-Identifier: MIT\n"
         @"\n"
         @"// Camera curves and gamut matrices: OpenColorIO Config ACES v4.0\n"
         @"// (BSD-3-Clause). Fujifilm F-Log / F-Log2 and Nikon N-Log are not "
         @"in that\n"
         @"// config; their coefficients are the vendor-published ones, "
         @"cross-checked\n"
         @"// against Colour (colour-science.org, BSD-3-Clause).\n"
         @"// #template color-transform\n"
         @"// #motionblur off\n"
         @"\n"
         @"// Both menus name a real space, because a transform cannot start "
         @"from\n"
         @"// \"unknown\". Final Cut hands this template LINEAR host values, "
         @"so an ordinary\n"
         @"// colour-managed SDR clip is already `Linear Rec.709` - the "
         @"default pair is\n"
         @"// that space in and out, an exact identity on drop. The encoded "
         @"choices (sRGB,\n"
         @"// Rec.709, Display P3, HLG, PQ, and every camera log) are for "
         @"footage whose\n"
         @"// curve the host has NOT already undone. To bypass, set Mix to 0.\n"
         @"//\n"
         @"// Every OUTPUT is a linear space. Final Cut owns the display "
         @"encode, so writing\n"
         @"// HLG or PQ code values here would encode twice; deliver HDR by "
         @"transforming to\n"
         @"// Linear Rec.2020 and letting the project's output do the rest.\n"
         @"//\n"
         @"// The HDR inputs put diffuse white at 1.0, the same place SDR "
         @"footage puts it:\n"
         @"// BT.2408 reference white, which is 203 nits for PQ and signal "
         @"0.75 for HLG.\n"
         @"// Specular highlights land above 1.0, which the float surface "
         @"holds. HLG gets\n"
         @"// its inverse OETF only - the OOTF is display rendering, and a "
         @"technical\n"
         @"// transform stays out of the look business.\n"
         @"// #choice label=\"Input\" group={\"Transform\", "
         @"\"arrow.down.right\"} dropdown options=\"Linear Rec.709,Linear "
         @"Display P3,Linear Rec.2020,sRGB,Rec.709,Display P3,Rec.2020 "
         @"HLG,Rec.2020 PQ,ACES2065-1,ACEScg,ACEScct,Apple Log / Rec.2020,ARRI "
         @"LogC3 / AWG3,ARRI LogC4 / AWG4,Blackmagic Film Gen 5,Canon C-Log2 / "
         @"Cinema Gamut,Canon C-Log3 / Cinema Gamut,DaVinci Intermediate,DJI "
         @"D-Log / D-Gamut,Fujifilm F-Log / F-Gamut,Fujifilm F-Log2 / "
         @"F-Gamut,Nikon N-Log / Rec.2020,Panasonic V-Log / V-Gamut,RED "
         @"Log3G10 / RWG,Sony S-Log2 / S-Gamut,Sony S-Log3 / S-Gamut3,Sony "
         @"S-Log3 / S-Gamut3.Cine\" default=0\n"
         @"uniform int uInput;\n"
         @"\n"
         @"// #choice label=\"Output\" group=\"Transform\" dropdown "
         @"options=\"Linear Rec.709,Linear Display P3,Linear "
         @"Rec.2020,ACEScg,ACES2065-1\" default=0\n"
         @"uniform int uOutput;\n"
         @"\n"
         @"// #percent label=\"Mix\" group=\"Transform\" default=100\n"
         @"uniform float uMix;\n"
         @"\n"
         @"vec3 rows(vec3 c, vec3 r0, vec3 r1, vec3 r2)\n"
         @"{\n"
         @"\treturn vec3(dot(r0, c), dot(r1, c), dot(r2, c));\n"
         @"}\n"
         @"\n"
         @"float srgbToLinear(float x)\n"
         @"{\n"
         @"\treturn x <= 0.04045 ? x / 12.92 : pow((x + 0.055) / 1.055, 2.4);\n"
         @"}\n"
         @"\n"
         @"float rec709ToLinear(float x)\n"
         @"{\n"
         @"\treturn x < 0.081 ? x / 4.5 : pow((x + 0.099) / 1.099, 1.0 / "
         @"0.45);\n"
         @"}\n"
         @"\n"
         @"// BT.2100 HLG, inverse OETF only, scaled so signal 0.75 (reference "
         @"white)\n"
         @"// lands on 1.0.\n"
         @"float hlgToLinear(float x)\n"
         @"{\n"
         @"\tconst float ha = 0.17883277;\n"
         @"\tconst float hb = 0.28466892;\n"
         @"\tconst float hc = 0.55991073;\n"
         @"\tfloat e = x <= 0.5 ? x * x / 3.0 : (exp((x - hc) / ha) + hb) / "
         @"12.0;\n"
         @"\treturn e * 3.7741181275;\n"
         @"}\n"
         @"\n"
         @"// SMPTE ST 2084 EOTF. Absolute nits, rescaled so BT.2408 reference "
         @"white\n"
         @"// (203 nits) lands on 1.0 and 10000 nits on 49.26.\n"
         @"float pqToLinear(float x)\n"
         @"{\n"
         @"\tfloat p = pow(max(x, 0.0), 1.0 / 78.84375);\n"
         @"\tfloat num = max(p - 0.8359375, 0.0);\n"
         @"\tfloat den = max(18.8515625 - 18.6875 * p, 1e-6);\n"
         @"\treturn pow(num / den, 1.0 / 0.1593017578125) * (10000.0 / "
         @"203.0);\n"
         @"}\n"
         @"\n"
         @"float acesCctToLinear(float x)\n"
         @"{\n"
         @"\treturn x <= 0.155251141552511\n"
         @"\t\t? (x - 0.0729055341958355) / 10.5402377416545\n"
         @"\t\t: pow(2.0, x * 17.52 - 9.72);\n"
         @"}\n"
         @"\n"
         @"float cameraLogToLinear(float y, float base, float linSlope, float "
         @"linOffset,\n"
         @"                        float logSlope, float logOffset, float "
         @"linBreak,\n"
         @"                        float toeSlope)\n"
         @"{\n"
         @"\tfloat q = linSlope * linBreak + linOffset;\n"
         @"\tfloat yBreak = logSlope * log(q) / log(base) + logOffset;\n"
         @"\tfloat slope = toeSlope > 0.0\n"
         @"\t\t? toeSlope\n"
         @"\t\t: logSlope * linSlope / (log(base) * q);\n"
         @"\treturn y >= yBreak\n"
         @"\t\t? (pow(base, (y - logOffset) / logSlope) - linOffset) / "
         @"linSlope\n"
         @"\t\t: linBreak + (y - yBreak) / slope;\n"
         @"}\n"
         @"\n"
         @"vec3 decodeLog(vec3 c, float base, float linSlope, float "
         @"linOffset,\n"
         @"               float logSlope, float logOffset, float linBreak, "
         @"float toeSlope)\n"
         @"{\n"
         @"\treturn vec3(cameraLogToLinear(c.r, base, linSlope, linOffset, "
         @"logSlope, logOffset, linBreak, toeSlope),\n"
         @"\t            cameraLogToLinear(c.g, base, linSlope, linOffset, "
         @"logSlope, logOffset, linBreak, toeSlope),\n"
         @"\t            cameraLogToLinear(c.b, base, linSlope, linOffset, "
         @"logSlope, logOffset, linBreak, toeSlope));\n"
         @"}\n"
         @"\n"
         @"float appleLogToLinear(float y)\n"
         @"{\n"
         @"\tconst float cut = 0.2085553160;\n"
         @"\treturn y < cut ? sqrt(max(y, 0.0) / 47.28711236) - 0.05641088\n"
         @"\t               : pow(2.0, (y - 0.69336945) / 0.08550479) - "
         @"0.00964052;\n"
         @"}\n"
         @"\n"
         @"float canonLog2ToLinear(float y)\n"
         @"{\n"
         @"\tfloat v = y < 0.092864125\n"
         @"\t\t? -(pow(10.0, (0.092864125 - y) / 0.24136077) - 1.0)\n"
         @"\t\t:  (pow(10.0, (y - 0.092864125) / 0.24136077) - 1.0);\n"
         @"\treturn 0.9 * v / 87.099375;\n"
         @"}\n"
         @"\n"
         @"float canonLog3ToLinear(float y)\n"
         @"{\n"
         @"\tif (y < 0.09746547)\n"
         @"\t\treturn -0.9 * (pow(10.0, (0.12783901 - y) / 0.36726845) - 1.0) "
         @"/ 14.98325;\n"
         @"\tif (y <= 0.15277891)\n"
         @"\t\treturn 0.9 * (y - 0.12512219) / 1.9754798;\n"
         @"\treturn 0.9 * (pow(10.0, (y - 0.12240537) / 0.36726845) - 1.0) / "
         @"14.98325;\n"
         @"}\n"
         @"\n"
         @"// F-Log and F-Log2 share one curve shape and differ only in "
         @"coefficients.\n"
         @"float fLogToLinear(float y, float cut2, float fa, float fb, float "
         @"fc, float fd,\n"
         @"                   float fe, float ff)\n"
         @"{\n"
         @"\treturn y < cut2 ? (y - ff) / fe\n"
         @"\t                : pow(10.0, (y - fd) / fc) / fa - fb / fa;\n"
         @"}\n"
         @"\n"
         @"float nLogToLinear(float y)\n"
         @"{\n"
         @"\treturn y < 0.4418377321603128\n"
         @"\t\t? pow(max(y, 0.0) / 0.635386119257087, 3.0) - 0.0075\n"
         @"\t\t: exp((y - 0.6050830889540567) / 0.1466275659824047);\n"
         @"}\n"
         @"\n"
         @"vec3 srgbToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(srgbToLinear(c.r), srgbToLinear(c.g), "
         @"srgbToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 rec709ToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(rec709ToLinear(c.r), rec709ToLinear(c.g), "
         @"rec709ToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 hlgToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(hlgToLinear(c.r), hlgToLinear(c.g), "
         @"hlgToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 pqToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(pqToLinear(c.r), pqToLinear(c.g), pqToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 acesCctToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(acesCctToLinear(c.r), acesCctToLinear(c.g), "
         @"acesCctToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 appleLogToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(appleLogToLinear(c.r), appleLogToLinear(c.g), "
         @"appleLogToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 canonLog2ToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(canonLog2ToLinear(c.r), canonLog2ToLinear(c.g), "
         @"canonLog2ToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 canonLog3ToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(canonLog3ToLinear(c.r), canonLog3ToLinear(c.g), "
         @"canonLog3ToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 fLogToLinear3(vec3 c, float cut2, float fa, float fb, float "
         @"fc, float fd,\n"
         @"                   float fe, float ff)\n"
         @"{\n"
         @"\treturn vec3(fLogToLinear(c.r, cut2, fa, fb, fc, fd, fe, ff),\n"
         @"\t            fLogToLinear(c.g, cut2, fa, fb, fc, fd, fe, ff),\n"
         @"\t            fLogToLinear(c.b, cut2, fa, fb, fc, fd, fe, ff));\n"
         @"}\n"
         @"\n"
         @"vec3 nLogToLinear3(vec3 c)\n"
         @"{\n"
         @"\treturn vec3(nLogToLinear(c.r), nLogToLinear(c.g), "
         @"nLogToLinear(c.b));\n"
         @"}\n"
         @"\n"
         @"vec3 rec709ToAP0(vec3 c)\n"
         @"{\n"
         @"\treturn rows(c, vec3(0.4396329819, 0.3829886982, 0.1773783199),\n"
         @"\t               vec3(0.0897764430, 0.8134394287, 0.0967841283),\n"
         @"\t               vec3(0.0175411704, 0.1115465533, 0.8709122763));\n"
         @"}\n"
         @"\n"
         @"vec3 p3ToAP0(vec3 c)\n"
         @"{\n"
         @"\treturn rows(c, vec3(0.5189334876, 0.2862565864, 0.1948099260),\n"
         @"\t               vec3(0.0738593830, 0.8198451639, 0.1062954530),\n"
         @"\t               vec3(-0.0003070114, 0.0438070503, 0.9564999611));\n"
         @"}\n"
         @"\n"
         @"// F-Gamut and Nikon's N-Log gamut are Rec.2020 primaries, so they "
         @"share this.\n"
         @"vec3 rec2020ToAP0(vec3 c)\n"
         @"{\n"
         @"\treturn rows(c, vec3(0.6790856347, 0.1577009146, 0.1632134507),\n"
         @"\t               vec3(0.0460020031, 0.8590546730, 0.0949433239),\n"
         @"\t               vec3(-0.0005739432, 0.0284677684, 0.9721061748));\n"
         @"}\n"
         @"\n"
         @"vec3 ap1ToAP0(vec3 c)\n"
         @"{\n"
         @"\treturn rows(c, vec3(0.6954522414, 0.1406786965, 0.1638690622),\n"
         @"\t               vec3(0.0447945634, 0.8596711185, 0.0955343182),\n"
         @"\t               vec3(-0.0055258826, 0.0040252103, 1.0015006723));\n"
         @"}\n"
         @"\n"
         @"vec3 inputToAP0(vec3 c, int inputID)\n"
         @"{\n"
         @"\tif (inputID == 0) return rec709ToAP0(c);\n"
         @"\tif (inputID == 1) return p3ToAP0(c);\n"
         @"\tif (inputID == 2) return rec2020ToAP0(c);\n"
         @"\n"
         @"\tif (inputID == 3) return rec709ToAP0(srgbToLinear3(c));\n"
         @"\tif (inputID == 4) return rec709ToAP0(rec709ToLinear3(c));\n"
         @"\tif (inputID == 5) return p3ToAP0(srgbToLinear3(c));\n"
         @"\tif (inputID == 6) return rec2020ToAP0(hlgToLinear3(c));\n"
         @"\tif (inputID == 7) return rec2020ToAP0(pqToLinear3(c));\n"
         @"\n"
         @"\tif (inputID == 8) return c;\n"
         @"\tif (inputID == 9) return ap1ToAP0(c);\n"
         @"\tif (inputID == 10) return ap1ToAP0(acesCctToLinear3(c));\n"
         @"\n"
         @"\tif (inputID == 11) return rec2020ToAP0(appleLogToLinear3(c));\n"
         @"\tif (inputID == 12) {\n"
         @"\t\tc = decodeLog(c, 10.0, 5.5555555556, 0.0522722750, "
         @"0.2471896383, 0.3855369987, 0.0105909905, 0.0);\n"
         @"\t\treturn rows(c, vec3(0.6802055051, 0.2361366016, 0.0836578933), "
         @"vec3(0.0854149797, 1.0174708786, -0.1028858583), vec3(0.0020565217, "
         @"-0.0625625004, 1.0605059787));\n"
         @"\t}\n"
         @"\tif (inputID == 13) {\n"
         @"\t\tc = decodeLog(c, 2.0, 2231.8263090677, 64.0, 0.0647954196, "
         @"-0.2959083927, -0.0180569961, 0.0);\n"
         @"\t\treturn rows(c, vec3(0.7509573628, 0.1444227867, 0.1046198505), "
         @"vec3(0.0008218371, 1.0073975849, -0.0082194220), "
         @"vec3(-0.0004999521, -0.0008541772, 1.0013541294));\n"
         @"\t}\n"
         @"\tif (inputID == 14) {\n"
         @"\t\tc = decodeLog(c, 2.7182818285, 1.0, 0.0054940724, 0.0869287607, "
         @"0.5300133392, 0.005, 0.0);\n"
         @"\t\treturn rows(c, vec3(0.6470913256, 0.2425953851, 0.1103132893), "
         @"vec3(0.0651915997, 1.0250475676, -0.0902391673), "
         @"vec3(-0.0275570729, -0.0805887097, 1.1081457826));\n"
         @"\t}\n"
         @"\tif (inputID == 15 || inputID == 16) {\n"
         @"\t\tc = inputID == 15 ? canonLog2ToLinear3(c) : "
         @"canonLog3ToLinear3(c);\n"
         @"\t\treturn rows(c, vec3(0.7630644548, 0.1490211611, 0.0879143841), "
         @"vec3(0.0036574567, 1.1069603804, -0.1106178371), "
         @"vec3(-0.0094077940, -0.2183833050, 1.2277910990));\n"
         @"\t}\n"
         @"\tif (inputID == 17) {\n"
         @"\t\tc = decodeLog(c, 2.0, 1.0, 0.0075, 0.07329248, 0.51304736, "
         @"0.00262409, 10.44426855);\n"
         @"\t\treturn rows(c, vec3(0.7482702903, 0.1676946596, 0.0840350502), "
         @"vec3(0.0208421235, 1.1119047427, -0.1327468662), "
         @"vec3(-0.0915122574, -0.1277467128, 1.2192589702));\n"
         @"\t}\n"
         @"\tif (inputID == 18) {\n"
         @"\t\tc = decodeLog(c, 10.0, 0.9892, 0.0108, 0.2566629707, "
         @"0.5845550491, 0.0075807868, 0.0);\n"
         @"\t\treturn rows(c, vec3(0.6912792456, 0.2143825277, 0.0943382267), "
         @"vec3(0.0662224038, 1.0116160802, -0.0778384840), "
         @"vec3(-0.0172985410, -0.0773788501, 1.0946773911));\n"
         @"\t}\n"
         @"\tif (inputID == 19)\n"
         @"\t\treturn rec2020ToAP0(fLogToLinear3(c, 0.1005377752, 0.555556, "
         @"0.009468, 0.344676, 0.790453, 8.735631, 0.092864));\n"
         @"\tif (inputID == 20)\n"
         @"\t\treturn rec2020ToAP0(fLogToLinear3(c, 0.1006866854, 5.555556, "
         @"0.064829, 0.245281, 0.384316, 8.799461, 0.092864));\n"
         @"\tif (inputID == 21) return rec2020ToAP0(nLogToLinear3(c));\n"
         @"\tif (inputID == 22) {\n"
         @"\t\tc = decodeLog(c, 10.0, 1.0, 0.00873, 0.241514, 0.598206, 0.01, "
         @"0.0);\n"
         @"\t\treturn rows(c, vec3(0.7246167041, 0.1669152882, 0.1084680077), "
         @"vec3(0.0213902454, 0.9849081557, -0.0062984011), "
         @"vec3(-0.0092355629, -0.0010569056, 1.0102924685));\n"
         @"\t}\n"
         @"\tif (inputID == 23) {\n"
         @"\t\tc = decodeLog(c, 10.0, 155.975327, 2.55975327, 0.224282, 0.0, "
         @"-0.01, 0.0);\n"
         @"\t\treturn rows(c, vec3(0.7850588041, 0.0838587565, 0.1310824394), "
         @"vec3(0.0231738348, 1.0878975492, -0.1110713840), "
         @"vec3(-0.0737604354, -0.3145900723, 1.3883505077));\n"
         @"\t}\n"
         @"\t// S-Gamut and S-Gamut3 have the same primaries, so S-Log2 and "
         @"S-Log3 share\n"
         @"\t// one matrix; only S-Gamut3.Cine differs.\n"
         @"\tif (inputID == 24)\n"
         @"\t\tc = decodeLog(c, 10.0, 0.7864028412, 0.037584, 0.3705223109, "
         @"0.6162444731, -0.0000815322, 3.3670033670);\n"
         @"\telse\n"
         @"\t\tc = decodeLog(c, 10.0, 5.2631578947, 0.0526315789, "
         @"0.2556207234, 0.4105571848, 0.01125, 6.6219437118);\n"
         @"\tif (inputID == 26)\n"
         @"\t\treturn rows(c, vec3(0.6387886672, 0.2723514337, 0.0888598991), "
         @"vec3(-0.0039159060, 1.0880732309, -0.0841573249), "
         @"vec3(-0.0299072021, -0.0264325799, 1.0563397820));\n"
         @"\treturn rows(c, vec3(0.7529825954, 0.1433702162, 0.1036471884), "
         @"vec3(0.0217076974, 1.0153188355, -0.0370265329), "
         @"vec3(-0.0094160527, 0.0033704179, 1.0060456349));\n"
         @"}\n"
         @"\n"
         @"vec3 fromAP0(vec3 c, int outputID)\n"
         @"{\n"
         @"\tif (outputID == 4) return c;\n"
         @"\tif (outputID == 3)\n"
         @"\t\treturn rows(c, vec3(1.4514393161, -0.2365107469, "
         @"-0.2149285693),\n"
         @"\t\t               vec3(-0.0765537734, 1.1762296998, "
         @"-0.0996759264),\n"
         @"\t\t               vec3(0.0083161484, -0.0060324498, "
         @"0.9977163014));\n"
         @"\tif (outputID == 2)\n"
         @"\t\treturn rows(c, vec3(1.4904095205, -0.2661709193, "
         @"-0.2242386013),\n"
         @"\t\t               vec3(-0.0801674999, 1.1821671211, "
         @"-0.1019996212),\n"
         @"\t\t               vec3(0.0032276312, -0.0347764757, "
         @"1.0315488446));\n"
         @"\tif (outputID == 1)\n"
         @"\t\treturn rows(c, vec3(2.0249052860, -0.6890697610, "
         @"-0.3358355249),\n"
         @"\t\t               vec3(-0.1835970323, 1.2895062078, "
         @"-0.1059091755),\n"
         @"\t\t               vec3(0.0090585611, -0.0592796841, "
         @"1.0502211229));\n"
         @"\treturn rows(c, vec3(2.5216861867, -1.1341309882, -0.3875551985),\n"
         @"\t               vec3(-0.2764799142, 1.3727190877, -0.0962391734),\n"
         @"\t               vec3(-0.0153780650, -0.1529753359, "
         @"1.1683534008));\n"
         @"}\n"
         @"\n"
         @"void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
         @"{\n"
         @"\tvec4 source = texture(iChannel0, fragCoord / iResolution.xy);\n"
         @"\tif (source.a <= 0.000001) {\n"
         @"\t\tfragColor = vec4(0.0);\n"
         @"\t\treturn;\n"
         @"\t}\n"
         @"\tvec3 straight = source.rgb / source.a;\n"
         @"\tvec3 transformed = fromAP0(inputToAP0(straight, uInput), "
         @"uOutput);\n"
         @"\tfragColor = vec4(mix(straight, transformed, uMix), source.a);\n"
         @"}\n";
}

// The shipped transform: position, anchor, 3-axis rotation with a real
// perspective, scale, source blur and opacity. The former standalone
// MagicMove plugin, now a shader.
//
// Multi-pass, but NOT feedback - Buffer B is a pure function of the current
// source and Blur - so accumulate motion blur still works: the buffer is
// encoded once and every sub-sample reads it.
NSString *MirageMagicMoveShaderSource(void) {
  return @"// SPDX-FileCopyrightText: 2026 overpolish\n"
         @"// SPDX-License-Identifier: MIT\n"
         @"\n"
         @"// #template layout\n"
         @"\n"
         @"// Inverse transform: for each output pixel, undo the transform to "
         @"find where it\n"
         @"// came from in the source. That is why the maths reads backwards - "
         @"a scale of\n"
         @"// 200% divides.\n"
         @"// #motionblur on\n"
         @"// #alpha\n"
         @"\n"
         @"// `#point` uniforms arrive in PIXELS (bottom-origin), but "
         @"`default=` is in the\n"
         @"// lane's stored 0..1 fraction - hence 0.5 for centred.\n"
         @"// #point label=\"Position\" group={\"Transform\", \"move.3d\"} "
         @"osc=position default=\"0.5,0.5\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// The pivot rotation and scale turn about.\n"
         @"// #point label=\"Anchor\" group=\"Transform\" osc=point square "
         @"default=\"0.5,0.5\"\n"
         @"uniform vec2 uAnchor;\n"
         @"\n"
         @"// The box OSC comes from the `osc=box` sugar like every other "
         @"Mirage control:\n"
         @"// centred on the Position handle (`link=`), aspect-locked from "
         @"`lockaspect`, and\n"
         @"// sized on the shared ring curve so it matches the rest of the "
         @"plugin.\n"
         @"// The box sits on the pivot (Position + the anchor's offset from "
         @"centre) and\n"
         @"// grows FROM it: `anchor=` pins the anchor side, so an anchor in "
         @"a corner\n"
         @"// keeps that corner put and grows the opposite one, matching how "
         @"the render\n"
         @"// scales. `link=` alone would centre the box on the pivot and "
         @"grow it evenly\n"
         @"// in all directions.\n"
         @"// #multi percent label=\"Scale\" group=\"Transform\" fields={X,Y} "
         @"lockaspect osc=box link=\"uPosition + uAnchor - vec2(0.5)\" "
         @"anchor=uAnchor min={1,1} max={800,800} default=\"100,100\"\n"
         @"uniform vec2 uScale;\n"
         @"\n"
         @"// X and Y tip the picture in perspective, Z spins it in plane. The "
         @"rings sit\n"
         @"// on the true pivot - the anchor OFFSET from centre, applied to "
         @"Position -\n"
         @"// so they stay on it when Position moves, not just when the "
         @"anchor does.\n"
         @"// #multi label=\"Rotation\" group=\"Transform\" fields={X,Y,Z} "
         @"osc={rotate x,y,z} link=\"uPosition + uAnchor - vec2(0.5)\" "
         @"default=\"0,0,0\"\n"
         @"uniform vec3 uRotation;\n"
         @"\n"
         @"// Gaussian on the SOURCE, before the transform, so a blurred clip "
         @"that then\n"
         @"// rotates keeps its blur square to itself. Percent of the frame's "
         @"short side.\n"
         @"// Applied in Buffer B; this pass only samples the result.\n"
         @"// #percent label=\"Blur\" group=\"Transform\" min=0 max=100 "
         @"default=0\n"
         @"uniform float uBlur;\n"
         @"\n"
         @"// #percent label=\"Opacity\" group=\"Transform\" min=0 max=100 "
         @"default=100\n"
         @"uniform float uOpacity;\n"
         @"\n"
         @"// Eye distance from the picture plane, in half-frames: sets how "
         @"violent the\n"
         @"// keystone is on an X/Y tip. Hard-coded in the archived plugin "
         @"too.\n"
         @"const float kEyeDistance = 2.0;\n"
         @"\n"
         @"void mainImage(out vec4 fragColor, in vec2 fragCoord)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\tfloat aspect = res.x / res.y;\n"
         @"\n"
         @"\tvec2 p = fragCoord / res - uPosition / res;\n"
         @"\tvec2 anchor = uAnchor / res - 0.5;\n"
         @"\tp -= anchor;\n"
         @"\tp.x *= aspect;\n"
         @"\n"
         @"\t// Already radians and already negated - the wrapper emits\n"
         @"\t// `radians(-lane)`. Y is flipped because the archived shader "
         @"mirrored Y\n"
         @"\t// into the ray and back, which cancels for Ry but inverts Rx and "
         @"Rz.\n"
         @"\tvec3 rad = uRotation * vec3(1.0, -1.0, 1.0);\n"
         @"\tfloat cx = cos(rad.x), sx = sin(rad.x);\n"
         @"\tfloat cy = cos(rad.y), sy = sin(rad.y);\n"
         @"\tfloat cz = cos(rad.z), sz = sin(rad.z);\n"
         @"\tvec3 col0 = vec3(cy * cz + sy * sx * sz, cx * sz, -sy * cz + cy * "
         @"sx * sz);\n"
         @"\tvec3 col1 = vec3(-cy * sz + sy * sx * cz, cx * cz, sy * sz + cy * "
         @"sx * cz);\n"
         @"\tvec3 col2 = vec3(sy * cx, -sx, cy * cx);\n"
         @"\n"
         @"\t// Ray from the eye through this pixel, rotated into the "
         @"picture's frame:\n"
         @"\t// where it crosses the picture plane is the source pixel. Doing "
         @"it as a ray\n"
         @"\t// is what makes an X/Y tip a real perspective instead of a "
         @"squash.\n"
         @"\tvec3 Ow = vec3(0.0, 0.0, -kEyeDistance);\n"
         @"\tvec3 Dw = vec3(p.x, p.y, kEyeDistance);\n"
         @"\tvec3 O = vec3(dot(col0, Ow), dot(col1, Ow), dot(col2, Ow));\n"
         @"\tvec3 D = vec3(dot(col0, Dw), dot(col1, Dw), dot(col2, Dw));\n"
         @"\n"
         @"\tif (abs(D.z) < 0.0001)\n"
         @"\t{\n"
         @"\t\tfragColor = vec4(0.0);\n"
         @"\t\treturn;\n"
         @"\t}\n"
         @"\n"
         @"\tfloat tHit = -O.z / D.z;\n"
         @"\n"
         @"\t// Behind the eye: the far half of a picture tipped past 90 "
         @"degrees, which\n"
         @"\t// would otherwise fold back through itself and mirror.\n"
         @"\tif (tHit <= 0.0)\n"
         @"\t{\n"
         @"\t\tfragColor = vec4(0.0);\n"
         @"\t\treturn;\n"
         @"\t}\n"
         @"\n"
         @"\tp = vec2(O.x + tHit * D.x, O.y + tHit * D.y);\n"
         @"\tp.x /= aspect;\n"
         @"\n"
         @"\tif (abs(uScale.x) < 0.001 || abs(uScale.y) < 0.001)\n"
         @"\t{\n"
         @"\t\tfragColor = vec4(0.0);\n"
         @"\t\treturn;\n"
         @"\t}\n"
         @"\n"
         @"\tp /= uScale;\n"
         @"\tvec2 src = p + anchor + 0.5;\n"
         @"\n"
         @"\t// fwidth is in output pixels after the inverse map, so the "
         @"feather widens\n"
         @"\t// automatically as the picture is scaled down.\n"
         @"\tvec2 fw = fwidth(src);\n"
         @"\tfloat edgeAA = smoothstep(0.0, fw.x, src.x)\n"
         @"\t               * smoothstep(0.0, fw.x, 1.0 - src.x)\n"
         @"\t               * smoothstep(0.0, fw.y, src.y)\n"
         @"\t               * smoothstep(0.0, fw.y, 1.0 - src.y);\n"
         @"\n"
         @"\tif (edgeAA <= 0.0)\n"
         @"\t{\n"
         @"\t\tfragColor = vec4(0.0);\n"
         @"\t\treturn;\n"
         @"\t}\n"
         @"\n"
         @"\t// Buffer B holds the blurred source, built once for the whole "
         @"frame. Under\n"
         @"\t// motion blur this pass re-runs per sub-sample and each one is a "
         @"single\n"
         @"\t// fetch, instead of every sample re-blurring the same source.\n"
         @"\tvec4 c = texture(iChannel1, src);\n"
         @"\n"
         @"\t// `#alpha` makes the wrapper premultiply on output, so this must "
         @"return\n"
         @"\t// STRAIGHT colour - the source arrives premultiplied, hence the "
         @"divide.\n"
         @"\t// The blur above deliberately accumulates premultiplied, which "
         @"is the\n"
         @"\t// correct space to filter in.\n"
         @"\tfloat outA = c.a * uOpacity * edgeAA;\n"
         @"\tfragColor = (c.a > 0.0001) ? vec4(c.rgb / c.a, outA) : "
         @"vec4(0.0);\n"
         @"}\n";
}

// MagicMove's Buffer B: the source blur, computed once per frame so the
// Image pass costs ONE fetch per motion-blur sub-sample instead of
// re-blurring the same source N times.
//
// Buffer A is skipped: channel routing is positional, so a present Buffer A
// would seize iChannel0 and this pass would lose the source clip.
NSString *MirageMagicMoveBufferBSource(void) {
  return @"// Pool-alignment prefix: a VERBATIM copy of the Image section's "
         @"directives, in\n"
         @"// the same order, up to the one this pass uses. Offsets are "
         @"assigned\n"
         @"// colours-first then scalars in source order, so an identical "
         @"prefix lands on\n"
         @"// identical slots. Nothing here may be reordered or omitted.\n"
         @"// #point label=\"Position\" osc=position default=\"0.5,0.5\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// #point label=\"Anchor\" osc=point square default=\"0.5,0.5\"\n"
         @"uniform vec2 uAnchor;\n"
         @"\n"
         @"// #multi percent label=\"Scale\" fields={X,Y} lockaspect min={1,1} "
         @"max={800,800} default=\"100,100\"\n"
         @"uniform vec2 uScale;\n"
         @"\n"
         @"// #multi label=\"Rotation\" fields={X,Y,Z} osc={rotate x,y,z} "
         @"default=\"0,0,0\"\n"
         @"uniform vec3 uRotation;\n"
         @"\n"
         @"// #percent label=\"Blur\" min=0 max=100 default=0\n"
         @"uniform float uBlur;\n"
         @"\n"
         @"// The source blur, computed ONCE per frame. The Image pass then "
         @"samples this\n"
         @"// with one fetch per motion-blur sub-sample instead of re-blurring "
         @"the same\n"
         @"// source N times - which is the whole reason the blur lives in a "
         @"buffer.\n"
         @"// Non-feedback (it reads iChannel0 only), so accumulate motion "
         @"blur shares it.\n"
         @"const int kTaps = 32;\n"
         @"const float kGoldenAngle = 2.39996323;\n"
         @"\n"
         @"float mmHash(vec2 p)\n"
         @"{\n"
         @"\tvec3 p3 = fract(vec3(p.xyx) * 0.1031);\n"
         @"\tp3 += dot(p3, p3.yzx + 33.33);\n"
         @"\treturn fract((p3.x + p3.y) * p3.z);\n"
         @"}\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\tvec2 uv = fc / res;\n"
         @"\tfloat sigmaPx = uBlur * min(res.x, res.y) * 0.1;\n"
         @"\n"
         @"\tif (sigmaPx < 0.25)\n"
         @"\t{\n"
         @"\t\tO = texture(iChannel0, uv);\n"
         @"\t\treturn;\n"
         @"\t}\n"
         @"\n"
         @"\tvec2 sigmaUV = vec2(sigmaPx) / res;\n"
         @"\tfloat a0 = mmHash(fc) * 6.2831853;\n"
         @"\tvec4 acc = vec4(0.0);\n"
         @"\tfloat wacc = 0.0;\n"
         @"\n"
         @"\tfor (int i = 0; i < kTaps; i++)\n"
         @"\t{\n"
         @"\t\tfloat fi = float(i) + 0.5;\n"
         @"\t\tfloat r = sqrt(fi / float(kTaps));\n"
         @"\t\tfloat a = a0 + fi * kGoldenAngle;\n"
         @"\t\tfloat w = exp(-2.0 * r * r);\n"
         @"\t\tacc += texture(iChannel0, uv + vec2(cos(a), sin(a)) * r * "
         @"sigmaUV * 2.0) * w;\n"
         @"\t\twacc += w;\n"
         @"\t}\n"
         @"\n"
         @"\tO = acc / wacc;\n"
         @"}\n";
}

// Shared by every Frame pass: the rounded-window SDF, a hash, and one half of
// a separable gaussian.
NSString *MirageFrameCommonSource(void) {
  return @"// Signed distance in pixels to the rounded edge, negative inside. "
         @"The p-norm\n"
         @"// handles the corner falloff outside; min(max(d.x, d.y), 0.0) "
         @"supplies real\n"
         @"// depth inside. Clamping that to zero saturates the interior at "
         @"-r, which makes\n"
         @"// any border wider than the corner radius read as \"near the "
         @"edge\" everywhere\n"
         @"// and flood the shape.\n"
         @"float roundedSDF(vec2 p, vec2 halfSize, float r, float radius01)\n"
         @"{\n"
         @"\tfloat power = mix(5.0, 2.0, radius01);\n"
         @"\tvec2 d = abs(p) - halfSize + r;\n"
         @"\tvec2 o = max(d, 0.0);\n"
         @"\tfloat outside = pow(pow(o.x, power) + pow(o.y, power), 1.0 / "
         @"power) - r;\n"
         @"\tfloat inside = min(max(d.x, d.y), 0.0);\n"
         @"\treturn outside + inside;\n"
         @"}\n"
         @"\n"
         @"// Cheap 2D hash: the glow's grain, and the blur's per-pixel "
         @"jitter.\n"
         @"float frameHash(vec2 p)\n"
         @"{\n"
         @"\tvec3 p3 = fract(vec3(p.xyx) * 0.1031);\n"
         @"\tp3 += dot(p3, p3.yzx + 33.33);\n"
         @"\treturn fract((p3.x + p3.y) * p3.z);\n"
         @"}\n"
         @"\n"
         @"// One half of a separable gaussian, radius in pixels. 33 taps have "
         @"to cover\n"
         @"// whatever Glow Size asks for, so at a wide radius the spacing is "
         @"far past a\n"
         @"// texel and the kernel undersamples itself - that's the banding. "
         @"`jit` offsets\n"
         @"// every pixel's tap positions by up to half a step, which turns "
         @"that banding\n"
         @"// into fine grain instead. At glow softness the grain is "
         @"invisible; the bands\n"
         @"// were not.\n"
         @"vec4 frameBlurTex(sampler2D tex, vec2 uv, vec2 dir, vec2 res, float "
         @"radiusPx,\n"
         @"                  float jit)\n"
         @"{\n"
         @"\tvec2 step = dir * (max(radiusPx, 1.0) / 16.0) / res;\n"
         @"\tvec4 acc = vec4(0.0);\n"
         @"\tfloat wacc = 0.0;\n"
         @"\tfor (int i = -16; i <= 16; i++)\n"
         @"\t{\n"
         @"\t\tfloat fi = float(i) + jit;\n"
         @"\t\tfloat x = fi / 16.0;\n"
         @"\t\tfloat w = exp(-4.5 * x * x);\n"
         @"\t\tacc += texture(tex, uv + step * fi) * w;\n"
         @"\t\twacc += w;\n"
         @"\t}\n"
         @"\treturn acc / wacc;\n"
         @"}\n";
}

// Frame's Buffer B: the PREP pass - the picture premultiplied by its own
// silhouette, exactly what the old Glow plugin fed to MPS. Blurring this and
// dividing the colour back out at the end is what makes the glow vary smoothly
// in every direction.
//
// Buffer A is skipped throughout: channel routing is positional, so a present
// Buffer A would seize iChannel0 and every pass would lose the source clip.
NSString *MirageFrameBufferBSource(void) {
  return @"// Pool-alignment prefix: a VERBATIM copy of the Image section's "
         @"first\n"
         @"// directives, in the same order. Offsets are assigned "
         @"colours-first then\n"
         @"// scalars in source order, so an identical prefix lands on "
         @"identical slots -\n"
         @"// that's the whole reason these are here, and why nothing may be "
         @"reordered or\n"
         @"// omitted. No `group=`: lanes come from the Image section alone.\n"
         @"// #color label=\"Border Color\" default=\"#FFFFFF\"\n"
         @"uniform vec4 uBorderColor;\n"
         @"\n"
         @"// #color label=\"Glow Color\" default=\"#FFFFFFB3\"\n"
         @"uniform vec4 uGlowColor;\n"
         @"\n"
         @"// #percent label=\"Radius\" min=0 max=100 default=20\n"
         @"uniform float uRadius;\n"
         @"\n"
         @"// #multi label=\"Crop\" fields={W,H,X,Y} units={px,px,px,px} "
         @"min={0,0,,} max={1,1,,} default=\"1,1,0,0\"\n"
         @"uniform vec4 uCrop;\n"
         @"\n"
         @"// #percent label=\"Size\" min=1 max=400 default=100\n"
         @"uniform float uSize;\n"
         @"\n"
         @"// #point label=\"Position\" default=\"0,0\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// #float label=\"Border Width\" units=\"px\" min=0 max=200 "
         @"default=0\n"
         @"uniform float uBorderWidth;\n"
         @"\n"
         @"// #float label=\"Glow Size\" units=\"px\" min=0 max=300 default=0\n"
         @"uniform float uGlowSize;\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\tfloat sz = max(uSize, 0.001);\n"
         @"\tvec2 halfSize = uCrop.xy * res * 0.5 * sz;\n"
         @"\tvec2 winCentre = vec2(uCrop.z + uCrop.x * 0.5,\n"
         @"\t                      1.0 - uCrop.w - uCrop.y * 0.5) * res;\n"
         @"\tvec2 p = fc - (winCentre + uPosition);\n"
         @"\tfloat r = uRadius * min(halfSize.x, halfSize.y);\n"
         @"\t// Grown by the border, so a bordered frame casts the glow of its "
         @"border\n"
         @"\t// rather than of the content inside it.\n"
         @"\tfloat d = roundedSDF(p, halfSize, r, uRadius) - uBorderWidth;\n"
         @"\tfloat ins = 1.0 - smoothstep(0.0, max(fwidth(d), 1e-4) * 2.0, "
         @"d);\n"
         @"\tvec2 srcUV = (winCentre + p / sz) / res;\n"
         @"\tvec3 c = texture(iChannel0, clamp(srcUV, vec2(0.0), "
         @"vec2(1.0))).rgb;\n"
         @"\tO = vec4(c * ins, ins); // premultiplied\n"
         @"}\n";
}

// Frame's Buffer C: horizontal half of the glow blur, over the prep in Buffer
// B (on ch1 - a later pass reads an earlier one's CURRENT output). The prefix
// is here only so `uGlowSize` lands on the right pool slot; the blur radius IS
// the glow size, so the blurred alpha ends up being the glow's falloff.
NSString *MirageFrameBufferCSource(void) {
  return @"// Pool-alignment prefix: a VERBATIM copy of the Image section's "
         @"first\n"
         @"// directives, in the same order. Offsets are assigned "
         @"colours-first then\n"
         @"// scalars in source order, so an identical prefix lands on "
         @"identical slots -\n"
         @"// that's the whole reason these are here, and why nothing may be "
         @"reordered or\n"
         @"// omitted. No `group=`: lanes come from the Image section alone.\n"
         @"// #color label=\"Border Color\" default=\"#FFFFFF\"\n"
         @"uniform vec4 uBorderColor;\n"
         @"\n"
         @"// #color label=\"Glow Color\" default=\"#FFFFFFB3\"\n"
         @"uniform vec4 uGlowColor;\n"
         @"\n"
         @"// #percent label=\"Radius\" min=0 max=100 default=20\n"
         @"uniform float uRadius;\n"
         @"\n"
         @"// #multi label=\"Crop\" fields={W,H,X,Y} units={px,px,px,px} "
         @"min={0,0,,} max={1,1,,} default=\"1,1,0,0\"\n"
         @"uniform vec4 uCrop;\n"
         @"\n"
         @"// #percent label=\"Size\" min=1 max=400 default=100\n"
         @"uniform float uSize;\n"
         @"\n"
         @"// #point label=\"Position\" default=\"0,0\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// #float label=\"Border Width\" units=\"px\" min=0 max=200 "
         @"default=0\n"
         @"uniform float uBorderWidth;\n"
         @"\n"
         @"// #float label=\"Glow Size\" units=\"px\" min=0 max=300 default=0\n"
         @"uniform float uGlowSize;\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\tO = frameBlurTex(iChannel1, fc / res, vec2(1.0, 0.0), res, "
         @"uGlowSize,\n"
         @"\t                 frameHash(fc) - 0.5);\n"
         @"}\n";
}

// Frame's Buffer D: vertical half, over Buffer C. No pass reads a channel at
// or above its own index, so this chain never trips the feedback path - which
// would cap it at KK_FEEDBACK_SIM_MAXDIM and re-simulate it every frame.
NSString *MirageFrameBufferDSource(void) {
  return @"// Pool-alignment prefix: a VERBATIM copy of the Image section's "
         @"first\n"
         @"// directives, in the same order. Offsets are assigned "
         @"colours-first then\n"
         @"// scalars in source order, so an identical prefix lands on "
         @"identical slots -\n"
         @"// that's the whole reason these are here, and why nothing may be "
         @"reordered or\n"
         @"// omitted. No `group=`: lanes come from the Image section alone.\n"
         @"// #color label=\"Border Color\" default=\"#FFFFFF\"\n"
         @"uniform vec4 uBorderColor;\n"
         @"\n"
         @"// #color label=\"Glow Color\" default=\"#FFFFFFB3\"\n"
         @"uniform vec4 uGlowColor;\n"
         @"\n"
         @"// #percent label=\"Radius\" min=0 max=100 default=20\n"
         @"uniform float uRadius;\n"
         @"\n"
         @"// #multi label=\"Crop\" fields={W,H,X,Y} units={px,px,px,px} "
         @"min={0,0,,} max={1,1,,} default=\"1,1,0,0\"\n"
         @"uniform vec4 uCrop;\n"
         @"\n"
         @"// #percent label=\"Size\" min=1 max=400 default=100\n"
         @"uniform float uSize;\n"
         @"\n"
         @"// #point label=\"Position\" default=\"0,0\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// #float label=\"Border Width\" units=\"px\" min=0 max=200 "
         @"default=0\n"
         @"uniform float uBorderWidth;\n"
         @"\n"
         @"// #float label=\"Glow Size\" units=\"px\" min=0 max=300 default=0\n"
         @"uniform float uGlowSize;\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\tO = frameBlurTex(iChannel2, fc / res, vec2(0.0, 1.0), res, "
         @"uGlowSize,\n"
         @"\t                 frameHash(fc + 17.0) - 0.5);\n"
         @"}\n";
}

// The shipped framing filter: crops the clip to a window, rounds it, and can
// border, shadow and pulse it. Masks with `// #alpha` so the corners are
// genuinely transparent and a lane below shows through.
//
// Every control is a directive lane and every handle an authored `// @osc`
// block, so what used to be a whole plugin is now one shader. All three blocks
// fold in the Position slide, so the box and the radius handle sit on the
// rectangle as drawn. The radius block omits `fromPos` deliberately: a scalar
// point is inverted numerically by the engine, so the inverse can't drift out
// of sync with `toPos` the way a hand-written one would.
NSString *MirageFrameShaderSource(void) {
  return @"// SPDX-FileCopyrightText: 2026 overpolish\n"
         @"// SPDX-License-Identifier: MIT\n"
         @"\n"
         @"// #template layout\n"
         @"\n"
         @"// #alpha\n"
         @"\n"
         @"// Multi-pass (the glow blur runs in Buffer B/C), so the plugin's\n"
         @"// accumulate blur is unavailable - MagicMove owns transform "
         @"motion.\n"
         @"// #motionblur off\n"
         @"\n"
         @"// #percent label=\"Radius\" group={\"Shape\", \"squareshape\"} "
         @"min=0 max=100 default=20\n"
         @"uniform float uRadius;\n"
         @"\n"
         @"// The window. W,H = size, X,Y = its top-left corner in the frame. "
         @"Moving or\n"
         @"// resizing it slides the window over content that stays put.\n"
         @"// #multi label=\"Crop\" group=\"Shape\" fields={W,H,X,Y} "
         @"units={px,px,px,px} min={0,0,,} max={1,1,,} default=\"1,1,0,0\"\n"
         @"uniform vec4 uCrop;\n"
         @"\n"
         @"// Scales the finished window, mask and content together, about its "
         @"own centre.\n"
         @"// Crop picks what you see, this picks how big it's drawn.\n"
         @"// #percent label=\"Size\" group={\"Transform\", "
         @"\"arrow.up.left.and.arrow.down.right\"} min=1 max=400 default=100\n"
         @"uniform float uSize;\n"
         @"\n"
         @"// Slides window and content together. 0,0 leaves it wherever Crop "
         @"put it.\n"
         @"// Pixels, bottom-origin.\n"
         @"// #point label=\"Position\" group=\"Transform\" default=\"0,0\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// Drawn outside the edge, so the frame sits around the content "
         @"instead of\n"
         @"// eating into it. Pixels, so it stays put if you resize the "
         @"window.\n"
         @"// #float label=\"Border Width\" group={\"Border\", "
         @"\"square.dashed\"} units=\"px\" min=0 max=200 default=0\n"
         @"uniform float uBorderWidth;\n"
         @"\n"
         @"// #color label=\"Border Color\" default=\"#FFFFFF\"\n"
         @"uniform vec4 uBorderColor;\n"
         @"\n"
         @"// 0 = off. Pixels, like the border.\n"
         @"// #float label=\"Glow Size\" group={\"Glow\", \"app.shadow\"} "
         @"units=\"px\" min=0 max=300 default=0\n"
         @"uniform float uGlowSize;\n"
         @"\n"
         @"// #color label=\"Glow Color\" default=\"#FFFFFFB3\"\n"
         @"uniform vec4 uGlowColor;\n"
         @"\n"
         @"// How soft the glow's edge is. Low keeps it tight to the shape, "
         @"high spreads\n"
         @"// it across the whole blur.\n"
         @"//\n"
         @"// Judge this in the VIEWER, not the mini. The viewer composites in "
         @"linear\n"
         @"// (float dest) and the mini in gamma (8-bit), which displays the "
         @"faint tail\n"
         @"// 3-5x brighter in the viewer - so the same value reads softer in "
         @"the mini.\n"
         @"// The viewer is the one that matches the export.\n"
         @"// #percent label=\"Glow Feather\" group=\"Glow\" min=0 max=100 "
         @"default=60\n"
         @"uniform float uGlowFeather;\n"
         @"\n"
         @"// +Y is up, so a drop shadow wants a negative Y. 0,0 gives an even "
         @"glow.\n"
         @"// #multi label=\"Glow Offset\" group=\"Glow\" fields={X,Y} "
         @"units={px,px} default=\"0,0\"\n"
         @"uniform vec2 uGlowOffset;\n"
         @"\n"
         @"// Takes the glow's colour from a blurred copy of the picture "
         @"(Buffer B/C)\n"
         @"// instead of from\n"
         @"// Glow Color, so it drifts with the shot the way an LED backdrop "
         @"does. 0 = the\n"
         @"// flat colour, 100% = all picture. Glow Color still sets the "
         @"strength through\n"
         @"// its alpha, so a black at 70% stays a 70% glow whatever colour it "
         @"picks up.\n"
         @"// #percent label=\"Glow Pickup\" group=\"Glow\" min=0 max=100 "
         @"default=0\n"
         @"uniform float uGlowPickup;\n"
         @"\n"
         @"// Grain in the glow, drifting outward - the aura look the old Glow "
         @"plugin had.\n"
         @"// 0 = clean.\n"
         @"// #percent label=\"Glow Noise\" group=\"Glow\" min=0 max=100 "
         @"default=0\n"
         @"uniform float uGlowNoise;\n"
         @"\n"
         @"// Grain cell size. Bigger = chunkier.\n"
         @"// #float label=\"Noise Scale\" group=\"Glow\" units=\"px\" min=1 "
         @"max=200 default=24\n"
         @"uniform float uNoiseScale;\n"
         @"\n"
         @"// How fast the grain drifts outward. 0 freezes it.\n"
         @"// #float label=\"Noise Speed\" group=\"Glow\" min=0 max=5 "
         @"default=1\n"
         @"uniform float uNoiseSpeed;\n"
         @"\n"
         @"// Light scattering off the bright parts of the picture, added on "
         @"top of the\n"
         @"// content rather than behind it. 0 = off.\n"
         @"// #percent label=\"Bloom\" group={\"Bloom\", \"sparkles\"} min=0 "
         @"max=200 default=0\n"
         @"uniform float uBloom;\n"
         @"\n"
         @"// How bright a pixel has to be before it blooms. Higher = only the "
         @"highlights.\n"
         @"// #percent label=\"Bloom Threshold\" group=\"Bloom\" min=0 max=100 "
         @"default=60\n"
         @"uniform float uBloomThreshold;\n"

         @"\n"
         @"// How far the glow dips between hits. 0 = steady, 100% = down to "
         @"nothing.\n"
         @"//\n"
         @"// Defaults to OFF, and that matters: with no audio bound every "
         @"band reads\n"
         @"// silent, which is indistinguishable from a quiet passage, so the "
         @"glow would\n"
         @"// sit permanently dimmed by this amount - at 100% it would vanish "
         @"outright, at\n"
         @"// any Glow Size. Raise it only once a source is picked below.\n"
         @"// #percent label=\"Pulse Amount\" group={\"Pulse\", \"metronome\"} "
         @"min=0 max=100 default=0\n"
         @"uniform float uPulseAmount;\n"
         @"\n"
         @"// #audio label=\"Pulse Audio\" gate=-50 release=0.18 smooth=0.07\n"
         @"uniform vec4 uPulseAudio[8];\n"
         @"\n"
         @"// How much each quarter of the spectrum drives it. One at 100% is "
         @"\"listen to\n"
         @"// that range\"; several open up a blend. Weights rather than a "
         @"picker so the\n"
         @"// ranges can overlap, and so they can be keyframed - a picker is "
         @"structural\n"
         @"// and can't animate.\n"
         @"// #multi label=\"Listen To\" group=\"Pulse\" fields={Bass,Low "
         @"Mid,High Mid,Treble} percent min=0 max=100 default=\"100,0,0,0\"\n"
         @"uniform vec4 uListenTo;\n"
         @"\n"
         @"// @osc Crop\n"
         @"//   primitive = box\n"
         @"//   binds     = uCrop\n"
         @"//   mid       = vec2(uCrop.z + uCrop.x * 0.5, 1.0 - uCrop.w - "
         @"uCrop.y * 0.5) + uPosition\n"
         @"//   half      = vec2(uCrop.x, uCrop.y) * 0.5 * uSize\n"
         @"//   toRect    = rect(mid - half, mid + half)\n"
         @"//   w         = rect.width / uSize\n"
         @"//   h         = rect.height / uSize\n"
         @"//   cx        = rect.min.x + rect.width * 0.5\n"
         @"//   cy        = rect.min.y + rect.height * 0.5\n"
         @"//   fromRect  = vec4(w, h, cx - uPosition.x - w * 0.5, 1.0 - cy + "
         @"uPosition.y - h * 0.5)\n"
         @"\n"
         @"// @osc Position\n"
         @"//   primitive = position\n"
         @"//   binds     = uPosition\n"
         @"//   mid       = vec2(uCrop.z + uCrop.x * 0.5, 1.0 - uCrop.w - "
         @"uCrop.y * 0.5)\n"
         @"//   toPos     = mid + uPosition\n"
         @"//   fromPos   = pos - mid\n"
         @"\n"
         @"// @osc Radius\n"
         @"//   primitive = point\n"
         @"//   binds     = uRadius\n"
         @"//   style     = hollow\n"
         @"//   cursor    = resize-diag\n"
         @"//   mid       = vec2(uCrop.z + uCrop.x * 0.5, 1.0 - uCrop.w - "
         @"uCrop.y * 0.5) + uPosition\n"
         @"//   half      = vec2(uCrop.x, uCrop.y) * 0.5 * uSize\n"
         @"//   corner    = mid + half\n"
         @"//   minH      = min(uCrop.x * uSize * aspect, uCrop.y * uSize)\n"
         @"//   power     = mix(5.0, 2.0, uRadius)\n"
         @"//   inset     = mix(1.0 - 1.0 / pow(2.0, 1.0 / power), 1.0 - 1.0 / "
         @"sqrt(2.0), uRadius)\n"
         @"//   corr      = 1.0 - 0.22 * sin(uRadius * pi)\n"
         @"//   pad       = minH * 0.05 + minH * 0.5 * uRadius * inset * corr\n"
         @"//   toPos     = corner - vec2(pad / aspect, pad)\n"
         @"\n"
         @"\n"
         @"// Peak level across a slice of the spectrum, given as fractions of "
         @"the whole.\n"
         @"// Slicing by fraction rather than by band index keeps \"Bass\" "
         @"meaning the same\n"
         @"// thing whatever band count the source reports. Constant loop "
         @"bound (the\n"
         @"// vec4[8] ceiling) with the range tested inside.\n"
         @"float bandPeak(float lo01, float hi01, int bands)\n"
         @"{\n"
         @"\tint lo = int(lo01 * float(bands));\n"
         @"\tint hi = max(lo, int(hi01 * float(bands)) - 1);\n"
         @"\tfloat lvl = 0.0;\n"
         @"\tfor (int i = 0; i < 32; i++)\n"
         @"\t{\n"
         @"\t\tif (i < lo || i > hi || i >= bands)\n"
         @"\t\t\tcontinue;\n"
         @"\t\tlvl = max(lvl, uPulseAudioBand(i)); // peak, so a transient "
         @"survives\n"
         @"\t}\n"
         @"\treturn lvl;\n"
         @"}\n"
         @"\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\n"
         @"\tfloat sz = max(uSize, 0.001); // guard the divide below\n"
         @"\n"
         @"\t// The window straight from Crop (top-left origin, Y down), "
         @"scaled about its\n"
         @"\t// own centre by Size.\n"
         @"\tvec2 halfSize = uCrop.xy * res * 0.5 * sz;\n"
         @"\tvec2 winCentre = vec2(uCrop.z + uCrop.x * 0.5,\n"
         @"\t                      1.0 - uCrop.w - uCrop.y * 0.5) * res;\n"
         @"\n"
         @"\t// Position arrives in pixels, bottom-origin, so no scale and no "
         @"flip.\n"
         @"\tvec2 offset = uPosition;\n"
         @"\tvec2 centre = winCentre + offset;\n"
         @"\n"
         @"\tvec2 p = fc - centre; // window: Crop, Size and Position\n"
         @"\t// Content magnifies with the window: divide the offset from the "
         @"centre by\n"
         @"\t// Size so the same crop region fills the resized frame. At sz = "
         @"1 this is\n"
         @"\t// (fc - offset) / res, i.e. content sitting in place.\n"
         @"\tvec2 srcUV = (winCentre + (fc - centre) / sz) / res;\n"
         @"\tvec4 s = texture(iChannel0, srcUV);\n"
         @"\n"
         @"\tfloat r = uRadius * min(halfSize.x, halfSize.y); // stays "
         @"proportional\n"
         @"\tfloat d = roundedSDF(p, halfSize, r, uRadius);\n"
         @"\tfloat aa = max(fwidth(d), 1e-4);\n"
         @"\n"
         @"\t// Breath: 0 = bottom of the dip, 1 = full glow.\n"
         @"\t//\n"
         @"\t// `uPulseAudioBands` is a COMPILE-TIME constant (the declared "
         @"array size),\n"
         @"\t// not a count of whether a source is bound - so this can't tell "
         @"silence\n"
         @"\t// from nothing-connected, and with no audio every band reads 0 "
         @"and breath\n"
         @"\t// collapses to 0. Pulse Amount defaulting to 0 is what keeps "
         @"that from\n"
         @"\t// dimming the glow of a shader nobody wired audio into.\n"
         @"\tfloat breath = 1.0;\n"
         @"\tint bands = uPulseAudioBands;\n"
         @"\tif (uPulseAmount > 0.0 && bands > 0)\n"
         @"\t{\n"
         @"\t\t// Each range scaled by its own weight, then the loudest wins. "
         @"Max, not\n"
         @"\t\t// sum: two loud ranges shouldn't read louder than the loudest "
         @"one, and\n"
         @"\t\t// a single weight at 100% behaves exactly like picking that "
         @"range.\n"
         @"\t\tfloat lvl = 0.0;\n"
         @"\t\tlvl = max(lvl, bandPeak(0.00, 0.25, bands) * uListenTo.x);\n"
         @"\t\tlvl = max(lvl, bandPeak(0.25, 0.50, bands) * uListenTo.y);\n"
         @"\t\tlvl = max(lvl, bandPeak(0.50, 0.75, bands) * uListenTo.z);\n"
         @"\t\tlvl = max(lvl, bandPeak(0.75, 1.00, bands) * uListenTo.w);\n"
         @"\t\tbreath = clamp(lvl, 0.0, 1.0);\n"
         @"\t}\n"
         @"\t// Amount sets how far the breath dips; at 0 the glow never "
         @"varies.\n"
         @"\tfloat lo = 1.0 - uPulseAmount;\n"
         @"\tfloat pulseA = mix(lo, 1.0, breath);                // intensity\n"
         @"\tfloat pulseS = mix(mix(lo, 1.0, 0.5), 1.0, breath); // size, half "
         @"as deep\n"
         @"\n"
         @"\tfloat bw = uBorderWidth;\n"
         @"\tfloat gs = uGlowSize * pulseS;\n"
         @"\n"
         @"\t// Content silhouette, plus the border's outer silhouette (the "
         @"same shape\n"
         @"\t// grown by bw). Filling that outer shape UNDER the content "
         @"leaves a ring of\n"
         @"\t// exactly bw with correct corner joins, so there's no band "
         @"maths.\n"
         @"\tfloat shape = 1.0 - smoothstep(0.0, aa * 2.0, d);\n"
         @"\tfloat outer = 1.0 - smoothstep(0.0, aa * 2.0, d - bw);\n"
         @"\n"
         @"\t// Glow follows the outer edge, so a bordered frame casts the "
         @"shadow of its\n"
         @"\t// border rather than of the content inside it.\n"
         @"\t// The blurred silhouette IS the glow: its alpha is the falloff "
         @"and its\n"
         @"\t// colour is the pickup, so the two can't disagree. There's no "
         @"separate\n"
         @"\t// analytic falloff any more - that was a second curve fighting "
         @"the blur,\n"
         @"\t// and its plateau near the edge is what read as a solid border. "
         @"Offsetting\n"
         @"\t// samples the blur, which is how the drop shadow moves.\n"
         @"\tfloat gA = 0.0;\n"
         @"\tvec3 glowRGB = uGlowColor.rgb;\n"
         @"\tif (gs > 0.0 && uGlowColor.a > 0.0)\n"
         @"\t{\n"
         @"\t\tvec4 gb = texture(iChannel3, (fc - uGlowOffset * res) / res);\n"
         @"\t\t// The blurred alpha IS the glow profile: outside the shape it "
         @"runs from\n"
         @"\t\t// ~0.5 at the edge down to 0 at the blur's limit. Feather is a "
         @"gamma on\n"
         @"\t\t// it - low tightens to the shape, high spreads across the "
         @"whole blur.\n"
         @"\t\t//\n"
         @"\t\t// It used to be 1 - smoothstep(0, edge, 1 - gb.a), which "
         @"zeroed\n"
         @"\t\t// everything below 1 - edge: at the default feather that "
         @"killed every\n"
         @"\t\t// pixel under gb.a 0.3 outright and left the rest peaking at "
         @"0.14\n"
         @"\t\t// alpha. That's why there was no glow at any size - a wider "
         @"blur just\n"
         @"\t\t// spread a field that had already been multiplied to nothing.\n"
         @"\t\tfloat t = 1.0 - gb.a;\n"
         @"\t\tgA = pow(clamp(gb.a, 0.0, 1.0), mix(3.0, 0.5, uGlowFeather)) *\n"
         @"\t\t     uGlowColor.a * pulseA;\n"
         @"\t\tif (uGlowNoise > 0.0)\n"
         @"\t\t{\n"
         @"\t\t\t// Grain flowing outward in bands, so it reads as energy "
         @"leaving the\n"
         @"\t\t\t// edge rather than static sitting on top. It rides on how "
         @"far\n"
         @"\t\t\t// through the glow this pixel is, which the blurred alpha "
         @"already\n"
         @"\t\t\t// tells us.\n"
         @"\t\t\tvec2 cell = floor(fc / max(uNoiseScale, 1.0));\n"
         @"\t\t\tfloat rp = t * 6.0 - iTime * uNoiseSpeed;\n"
         @"\t\t\tfloat band = floor(rp);\n"
         @"\t\t\tfloat blend = smoothstep(0.0, 1.0, fract(rp));\n"
         @"\t\t\tfloat n = mix(frameHash(cell + band * vec2(127.1, 311.7)),\n"
         @"\t\t\t              frameHash(cell + (band + 1.0) * vec2(127.1, "
         @"311.7)),\n"
         @"\t\t\t              blend);\n"
         @"\t\t\tgA *= clamp(1.0 - uGlowNoise * (1.0 - n), 0.0, 1.0);\n"
         @"\t\t}\n"
         @"\t\t// Hold the picked-up colour as far out as the glow is still "
         @"visible.\n"
         @"\t\t// This used to fade at gb.a 0.02, but the ALPHA carries well "
         @"past that\n"
         @"\t\t// - at a high Feather pow(0.02, 0.5) is still ~0.14 - so the "
         @"colour\n"
         @"\t\t// reverted to flat while the glow was plainly there, and the "
         @"handover\n"
         @"\t\t// showed as a ring. The threshold only exists to keep the "
         @"divide off\n"
         @"\t\t// values too small to carry colour.\n"
         @"\t\tif (uGlowPickup > 0.0)\n"
         @"\t\t\tglowRGB = mix(glowRGB, gb.rgb / max(gb.a, 4e-4),\n"
         @"\t\t\t              uGlowPickup * smoothstep(1e-4, 4e-4, gb.a));\n"
         @"\t}\n"
         @"\n"
         @"\n"
         @"\t// Content, clipped to the source frame.\n"
         @"\tfloat cA = shape;\n"
         @"\tif (any(lessThan(srcUV, vec2(0.0))) || any(greaterThan(srcUV, "
         @"vec2(1.0))))\n"
         @"\t\tcA = 0.0;\n"
         @"\n"
         @"\tfloat bA = (bw > 0.0) ? outer * uBorderColor.a : 0.0;\n"
         @"\n"
         @"\t// Premultiplied \"over\", back to front: glow, border, content.\n"
         @"\tvec4 acc = vec4(glowRGB * gA, gA);\n"
         @"\tacc = vec4(uBorderColor.rgb * bA + acc.rgb * (1.0 - bA),\n"
         @"\t           bA + acc.a * (1.0 - bA));\n"
         @"\tacc = vec4(s.rgb * cA + acc.rgb * (1.0 - cA), cA + acc.a * (1.0 - "
         @"cA));\n"
         @"\n"
         @"\t// Bloom last, and ADDED rather than composited: scattered light "
         @"doesn't\n"
         @"\t// occlude what's under it. Buffer C's alpha is the blurred "
         @"brightness of\n"
         @"\t// the picture, so thresholding it here picks the regions that "
         @"are bright on\n"
         @"\t// average - steadier than thresholding per-pixel before the "
         @"blur, which\n"
         @"\t// makes small highlights flicker in and out as they cross the "
         @"cutoff.\n"
         @"\tif (uBloom > 0.0)\n"
         @"\t{\n"
         @"\t\tvec4 b = texture(iChannel3, fc / res);\n"
         @"\t\tvec3 bc = b.a > 0.003 ? b.rgb / b.a : vec3(0.0);\n"
         @"\t\tfloat thr = uBloomThreshold;\n"
         @"\t\tfloat lit = smoothstep(thr, min(thr + 0.2, 1.0),\n"
         @"\t\t                       max(bc.r, max(bc.g, bc.b)));\n"
         @"\t\tacc.rgb += bc * lit * uBloom * cA;\n"
         @"\t}\n"
         @"\n"
         @"\t// `acc` is built premultiplied, but the `// #alpha` output path "
         @"does\n"
         @"\t// kk_outColor = vec4(rgb * alpha, alpha) - it premultiplies for "
         @"us, so\n"
         @"\t// mainImage has to hand back STRAIGHT colour. Returning "
         @"premultiplied here\n"
         @"\t// multiplied by alpha twice.\n"
         @"\t//\n"
         @"\t// That only shows where alpha is PARTIAL. Content and border sit "
         @"at alpha\n"
         @"\t// 1, where squaring changes nothing, so they always looked "
         @"correct; the\n"
         @"\t// glow was the only partial-alpha part, and it alone got crushed "
         @"- a white\n"
         @"\t// glow at alpha 0.3 rendering as 0.09. The original shader never "
         @"caught it\n"
         @"\t// because its glow defaulted to BLACK, which survives any number "
         @"of\n"
         @"\t// multiplications unchanged.\n"
         @"\tO = (acc.a > 1e-4) ? vec4(acc.rgb / acc.a, acc.a) : vec4(0.0);\n"

         @"}\n";
}

// Shown when the user's shader fails to compile (e.g. uses iChannel textures or
// has a syntax error): animated dark-red hazard stripes, so a broken shader
// reads as clearly broken instead of a stale / blank frame.
NSString *MirageCustomErrorShaderSource(void) {
  return @"void mainImage( out vec4 fragColor, in vec2 fragCoord ) {\n"
         @"    vec2 uv = fragCoord / iResolution.xy;\n"
         @"    float s = step(0.5, fract((uv.x + uv.y) * 10.0 - iTime));\n"
         @"    vec3 col = mix(vec3(0.22,0.0,0.0), vec3(0.5,0.02,0.02), s);\n"
         @"    fragColor = vec4(col, 1.0);\n"
         @"}\n";
}
