/*
 * SPDX-FileCopyrightText: 2026 overpolish
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 */

#import "MirageCustomShader.h"

#import "Constants.h" // declares MirageCustomDefaultShaderSource

// The two baked GLSL sources. Both are trivial image-shader bodies, so they
// always transpile - which is the point: they are the fallbacks every other
// path leans on when the user's own source is absent or broken.

// The default shader: the classic cosine-palette plasma, so Custom renders
// something alive out of the box (and seeds the editor). It also ships the two
// directive-driven on-screen controls the timing guide teaches on - a Center
// the pattern radiates from (a point handle) and a Scale (a ring around that
// centre) - so a fresh instance has real OSCs, not just code. Default values
// reproduce the plain plasma: Center at the frame middle, Scale 3.
NSString *MirageCustomDefaultShaderSource(void) {
  return @"// #point label=\"Center\" osc default=\"0.5,0.5\"\n"
         @"uniform vec2 uCenter;\n"
         @"// #float label=\"Scale\" osc=ring link=uCenter min=1 max=8 "
         @"default=3\n"
         @"uniform float uScale;\n"
         @"\n"
         @"void mainImage( out vec4 fragColor, in vec2 fragCoord ) {\n"
         @"    vec2 uv = (fragCoord - uCenter) / iResolution.xy;\n"
         @"    vec3 col = 0.5 + 0.5 * cos(iTime + uv.xyx * uScale + "
         @"vec3(0.0, 2.0, 4.0));\n"
         @"    fragColor = vec4(col, 1.0);\n"
         @"}\n";
}

// Shared by every Frame pass: the rounded-window SDF, a hash, and one half of
// a separable gaussian.
NSString *MirageFrameCommonSource(void) {
  return @"// Signed distance in pixels to the rounded edge, negative inside. "
         @"The p-norm\n"
         @"// handles the corner falloff outside; min(max(d.x, d.y), 0.0) "
         @"supplies real\n"
         @"// depth inside. Clamping that to zero saturates the interior at "
         @"-r, which makes\n"
         @"// any border wider than the corner radius read as \"near the "
         @"edge\" everywhere\n"
         @"// and flood the shape.\n"
         @"float roundedSDF(vec2 p, vec2 halfSize, float r, float radius01)\n"
         @"{\n"
         @"\tfloat power = mix(5.0, 2.0, radius01);\n"
         @"\tvec2 d = abs(p) - halfSize + r;\n"
         @"\tvec2 o = max(d, 0.0);\n"
         @"\tfloat outside = pow(pow(o.x, power) + pow(o.y, power), 1.0 / "
         @"power) - r;\n"
         @"\tfloat inside = min(max(d.x, d.y), 0.0);\n"
         @"\treturn outside + inside;\n"
         @"}\n"
         @"\n"
         @"// Cheap 2D hash: the glow's grain, and the blur's per-pixel "
         @"jitter.\n"
         @"float frameHash(vec2 p)\n"
         @"{\n"
         @"\tvec3 p3 = fract(vec3(p.xyx) * 0.1031);\n"
         @"\tp3 += dot(p3, p3.yzx + 33.33);\n"
         @"\treturn fract((p3.x + p3.y) * p3.z);\n"
         @"}\n"
         @"\n"
         @"// One half of a separable gaussian, radius in pixels. 33 taps have "
         @"to cover\n"
         @"// whatever Glow Size asks for, so at a wide radius the spacing is "
         @"far past a\n"
         @"// texel and the kernel undersamples itself - that's the banding. "
         @"`jit` offsets\n"
         @"// every pixel's tap positions by up to half a step, which turns "
         @"that banding\n"
         @"// into fine grain instead. At glow softness the grain is "
         @"invisible; the bands\n"
         @"// were not.\n"
         @"vec4 frameBlurTex(sampler2D tex, vec2 uv, vec2 dir, vec2 res, float "
         @"radiusPx,\n"
         @"                  float jit)\n"
         @"{\n"
         @"\tvec2 step = dir * (max(radiusPx, 1.0) / 16.0) / res;\n"
         @"\tvec4 acc = vec4(0.0);\n"
         @"\tfloat wacc = 0.0;\n"
         @"\tfor (int i = -16; i <= 16; i++)\n"
         @"\t{\n"
         @"\t\tfloat fi = float(i) + jit;\n"
         @"\t\tfloat x = fi / 16.0;\n"
         @"\t\tfloat w = exp(-4.5 * x * x);\n"
         @"\t\tacc += texture(tex, uv + step * fi) * w;\n"
         @"\t\twacc += w;\n"
         @"\t}\n"
         @"\treturn acc / wacc;\n"
         @"}\n";
}

// Frame's Buffer B: the PREP pass - the picture premultiplied by its own
// silhouette, exactly what the old Glow plugin fed to MPS. Blurring this and
// dividing the colour back out at the end is what makes the glow vary smoothly
// in every direction.
//
// Buffer A is skipped throughout: channel routing is positional, so a present
// Buffer A would seize iChannel0 and every pass would lose the source clip.
NSString *MirageFrameBufferBSource(void) {
  return @"// Pool-alignment prefix: a VERBATIM copy of the Image section's "
         @"first\n"
         @"// directives, in the same order. Offsets are assigned "
         @"colours-first then\n"
         @"// scalars in source order, so an identical prefix lands on "
         @"identical slots -\n"
         @"// that's the whole reason these are here, and why nothing may be "
         @"reordered or\n"
         @"// omitted. No `group=`: lanes come from the Image section alone.\n"
         @"// #color label=\"Border Color\" default=\"#FFFFFF\"\n"
         @"uniform vec4 uBorderColor;\n"
         @"\n"
         @"// #color label=\"Glow Color\" default=\"#FFFFFFB3\"\n"
         @"uniform vec4 uGlowColor;\n"
         @"\n"
         @"// #percent label=\"Radius\" min=0 max=100 default=20\n"
         @"uniform float uRadius;\n"
         @"\n"
         @"// #multi label=\"Crop\" fields={W,H,X,Y} units={px,px,px,px} "
         @"min={0,0,,} max={1,1,,} default=\"1,1,0,0\"\n"
         @"uniform vec4 uCrop;\n"
         @"\n"
         @"// #percent label=\"Size\" min=1 max=400 default=100\n"
         @"uniform float uSize;\n"
         @"\n"
         @"// #point label=\"Position\" default=\"0,0\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// #float label=\"Border Width\" units=\"px\" min=0 max=200 "
         @"default=0\n"
         @"uniform float uBorderWidth;\n"
         @"\n"
         @"// #float label=\"Glow Size\" units=\"px\" min=0 max=300 default=0\n"
         @"uniform float uGlowSize;\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\tfloat sz = max(uSize, 0.001);\n"
         @"\tvec2 halfSize = uCrop.xy * res * 0.5 * sz;\n"
         @"\tvec2 winCentre = vec2(uCrop.z + uCrop.x * 0.5,\n"
         @"\t                      1.0 - uCrop.w - uCrop.y * 0.5) * res;\n"
         @"\tvec2 p = fc - (winCentre + uPosition);\n"
         @"\tfloat r = uRadius * min(halfSize.x, halfSize.y);\n"
         @"\t// Grown by the border, so a bordered frame casts the glow of its "
         @"border\n"
         @"\t// rather than of the content inside it.\n"
         @"\tfloat d = roundedSDF(p, halfSize, r, uRadius) - uBorderWidth;\n"
         @"\tfloat ins = 1.0 - smoothstep(0.0, max(fwidth(d), 1e-4) * 2.0, "
         @"d);\n"
         @"\tvec2 srcUV = (winCentre + p / sz) / res;\n"
         @"\tvec3 c = texture(iChannel0, clamp(srcUV, vec2(0.0), "
         @"vec2(1.0))).rgb;\n"
         @"\tO = vec4(c * ins, ins); // premultiplied\n"
         @"}\n";
}

// Frame's Buffer C: horizontal half of the glow blur, over the prep in Buffer
// B (on ch1 - a later pass reads an earlier one's CURRENT output). The prefix
// is here only so `uGlowSize` lands on the right pool slot; the blur radius IS
// the glow size, so the blurred alpha ends up being the glow's falloff.
NSString *MirageFrameBufferCSource(void) {
  return @"// Pool-alignment prefix: a VERBATIM copy of the Image section's "
         @"first\n"
         @"// directives, in the same order. Offsets are assigned "
         @"colours-first then\n"
         @"// scalars in source order, so an identical prefix lands on "
         @"identical slots -\n"
         @"// that's the whole reason these are here, and why nothing may be "
         @"reordered or\n"
         @"// omitted. No `group=`: lanes come from the Image section alone.\n"
         @"// #color label=\"Border Color\" default=\"#FFFFFF\"\n"
         @"uniform vec4 uBorderColor;\n"
         @"\n"
         @"// #color label=\"Glow Color\" default=\"#FFFFFFB3\"\n"
         @"uniform vec4 uGlowColor;\n"
         @"\n"
         @"// #percent label=\"Radius\" min=0 max=100 default=20\n"
         @"uniform float uRadius;\n"
         @"\n"
         @"// #multi label=\"Crop\" fields={W,H,X,Y} units={px,px,px,px} "
         @"min={0,0,,} max={1,1,,} default=\"1,1,0,0\"\n"
         @"uniform vec4 uCrop;\n"
         @"\n"
         @"// #percent label=\"Size\" min=1 max=400 default=100\n"
         @"uniform float uSize;\n"
         @"\n"
         @"// #point label=\"Position\" default=\"0,0\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// #float label=\"Border Width\" units=\"px\" min=0 max=200 "
         @"default=0\n"
         @"uniform float uBorderWidth;\n"
         @"\n"
         @"// #float label=\"Glow Size\" units=\"px\" min=0 max=300 default=0\n"
         @"uniform float uGlowSize;\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\tO = frameBlurTex(iChannel1, fc / res, vec2(1.0, 0.0), res, "
         @"uGlowSize,\n"
         @"\t                 frameHash(fc) - 0.5);\n"
         @"}\n";
}

// Frame's Buffer D: vertical half, over Buffer C. No pass reads a channel at
// or above its own index, so this chain never trips the feedback path - which
// would cap it at KK_FEEDBACK_SIM_MAXDIM and re-simulate it every frame.
NSString *MirageFrameBufferDSource(void) {
  return @"// Pool-alignment prefix: a VERBATIM copy of the Image section's "
         @"first\n"
         @"// directives, in the same order. Offsets are assigned "
         @"colours-first then\n"
         @"// scalars in source order, so an identical prefix lands on "
         @"identical slots -\n"
         @"// that's the whole reason these are here, and why nothing may be "
         @"reordered or\n"
         @"// omitted. No `group=`: lanes come from the Image section alone.\n"
         @"// #color label=\"Border Color\" default=\"#FFFFFF\"\n"
         @"uniform vec4 uBorderColor;\n"
         @"\n"
         @"// #color label=\"Glow Color\" default=\"#FFFFFFB3\"\n"
         @"uniform vec4 uGlowColor;\n"
         @"\n"
         @"// #percent label=\"Radius\" min=0 max=100 default=20\n"
         @"uniform float uRadius;\n"
         @"\n"
         @"// #multi label=\"Crop\" fields={W,H,X,Y} units={px,px,px,px} "
         @"min={0,0,,} max={1,1,,} default=\"1,1,0,0\"\n"
         @"uniform vec4 uCrop;\n"
         @"\n"
         @"// #percent label=\"Size\" min=1 max=400 default=100\n"
         @"uniform float uSize;\n"
         @"\n"
         @"// #point label=\"Position\" default=\"0,0\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// #float label=\"Border Width\" units=\"px\" min=0 max=200 "
         @"default=0\n"
         @"uniform float uBorderWidth;\n"
         @"\n"
         @"// #float label=\"Glow Size\" units=\"px\" min=0 max=300 default=0\n"
         @"uniform float uGlowSize;\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\tO = frameBlurTex(iChannel2, fc / res, vec2(0.0, 1.0), res, "
         @"uGlowSize,\n"
         @"\t                 frameHash(fc + 17.0) - 0.5);\n"
         @"}\n";
}

// The shipped framing filter: crops the clip to a window, rounds it, and can
// border, shadow and pulse it. Masks with `// #alpha` so the corners are
// genuinely transparent and a lane below shows through.
//
// Every control is a directive lane and every handle an authored `// @osc`
// block, so what used to be a whole plugin is now one shader. All three blocks
// fold in the Position slide, so the box and the radius handle sit on the
// rectangle as drawn. The radius block omits `fromPos` deliberately: a scalar
// point is inverted numerically by the engine, so the inverse can't drift out
// of sync with `toPos` the way a hand-written one would.
NSString *MirageFrameShaderSource(void) {
  return @"// SPDX-FileCopyrightText: 2026 overpolish\n"
         @"// SPDX-License-Identifier: MIT\n"
         @"\n"
         @"// #alpha\n"
         @"\n"
         @"// Multi-pass (the glow blur runs in Buffer B/C), so the plugin's\n"
         @"// accumulate blur is unavailable - MagicMove owns transform "
         @"motion.\n"
         @"// #motionblur off\n"
         @"\n"
         @"// #percent label=\"Radius\" group={\"Shape\", \"squareshape\"} "
         @"min=0 max=100 default=20\n"
         @"uniform float uRadius;\n"
         @"\n"
         @"// The window. W,H = size, X,Y = its top-left corner in the frame. "
         @"Moving or\n"
         @"// resizing it slides the window over content that stays put.\n"
         @"// #multi label=\"Crop\" group=\"Shape\" fields={W,H,X,Y} "
         @"units={px,px,px,px} min={0,0,,} max={1,1,,} default=\"1,1,0,0\"\n"
         @"uniform vec4 uCrop;\n"
         @"\n"
         @"// Scales the finished window, mask and content together, about its "
         @"own centre.\n"
         @"// Crop picks what you see, this picks how big it's drawn.\n"
         @"// #percent label=\"Size\" group={\"Transform\", "
         @"\"arrow.up.left.and.arrow.down.right\"} min=1 max=400 default=100\n"
         @"uniform float uSize;\n"
         @"\n"
         @"// Slides window and content together. 0,0 leaves it wherever Crop "
         @"put it.\n"
         @"// Pixels, bottom-origin.\n"
         @"// #point label=\"Position\" group=\"Transform\" default=\"0,0\"\n"
         @"uniform vec2 uPosition;\n"
         @"\n"
         @"// Drawn outside the edge, so the frame sits around the content "
         @"instead of\n"
         @"// eating into it. Pixels, so it stays put if you resize the "
         @"window.\n"
         @"// #float label=\"Border Width\" group={\"Border\", "
         @"\"square.dashed\"} units=\"px\" min=0 max=200 default=0\n"
         @"uniform float uBorderWidth;\n"
         @"\n"
         @"// #color label=\"Border Color\" default=\"#FFFFFF\"\n"
         @"uniform vec4 uBorderColor;\n"
         @"\n"
         @"// 0 = off. Pixels, like the border.\n"
         @"// #float label=\"Glow Size\" group={\"Glow\", \"app.shadow\"} "
         @"units=\"px\" min=0 max=300 default=0\n"
         @"uniform float uGlowSize;\n"
         @"\n"
         @"// #color label=\"Glow Color\" default=\"#FFFFFFB3\"\n"
         @"uniform vec4 uGlowColor;\n"
         @"\n"
         @"// How soft the glow's edge is. Low keeps it tight to the shape, "
         @"high spreads\n"
         @"// it across the whole blur.\n"
         @"//\n"
         @"// Judge this in the VIEWER, not the mini. The viewer composites in "
         @"linear\n"
         @"// (float dest) and the mini in gamma (8-bit), which displays the "
         @"faint tail\n"
         @"// 3-5x brighter in the viewer - so the same value reads softer in "
         @"the mini.\n"
         @"// The viewer is the one that matches the export.\n"
         @"// #percent label=\"Glow Feather\" group=\"Glow\" min=0 max=100 "
         @"default=60\n"
         @"uniform float uGlowFeather;\n"
         @"\n"
         @"// +Y is up, so a drop shadow wants a negative Y. 0,0 gives an even "
         @"glow.\n"
         @"// #multi label=\"Glow Offset\" group=\"Glow\" fields={X,Y} "
         @"units={px,px} default=\"0,0\"\n"
         @"uniform vec2 uGlowOffset;\n"
         @"\n"
         @"// Takes the glow's colour from a blurred copy of the picture "
         @"(Buffer B/C)\n"
         @"// instead of from\n"
         @"// Glow Color, so it drifts with the shot the way an LED backdrop "
         @"does. 0 = the\n"
         @"// flat colour, 100% = all picture. Glow Color still sets the "
         @"strength through\n"
         @"// its alpha, so a black at 70% stays a 70% glow whatever colour it "
         @"picks up.\n"
         @"// #percent label=\"Glow Pickup\" group=\"Glow\" min=0 max=100 "
         @"default=0\n"
         @"uniform float uGlowPickup;\n"
         @"\n"
         @"// Grain in the glow, drifting outward - the aura look the old Glow "
         @"plugin had.\n"
         @"// 0 = clean.\n"
         @"// #percent label=\"Glow Noise\" group=\"Glow\" min=0 max=100 "
         @"default=0\n"
         @"uniform float uGlowNoise;\n"
         @"\n"
         @"// Grain cell size. Bigger = chunkier.\n"
         @"// #float label=\"Noise Scale\" group=\"Glow\" units=\"px\" min=1 "
         @"max=200 default=24\n"
         @"uniform float uNoiseScale;\n"
         @"\n"
         @"// How fast the grain drifts outward. 0 freezes it.\n"
         @"// #float label=\"Noise Speed\" group=\"Glow\" min=0 max=5 "
         @"default=1\n"
         @"uniform float uNoiseSpeed;\n"
         @"\n"
         @"// Light scattering off the bright parts of the picture, added on "
         @"top of the\n"
         @"// content rather than behind it. 0 = off.\n"
         @"// #percent label=\"Bloom\" group={\"Bloom\", \"sparkles\"} min=0 "
         @"max=200 default=0\n"
         @"uniform float uBloom;\n"
         @"\n"
         @"// How bright a pixel has to be before it blooms. Higher = only the "
         @"highlights.\n"
         @"// #percent label=\"Bloom Threshold\" group=\"Bloom\" min=0 max=100 "
         @"default=60\n"
         @"uniform float uBloomThreshold;\n"

         @"\n"
         @"// How far the glow dips between hits. 0 = steady, 100% = down to "
         @"nothing.\n"
         @"//\n"
         @"// Defaults to OFF, and that matters: with no audio bound every "
         @"band reads\n"
         @"// silent, which is indistinguishable from a quiet passage, so the "
         @"glow would\n"
         @"// sit permanently dimmed by this amount - at 100% it would vanish "
         @"outright, at\n"
         @"// any Glow Size. Raise it only once a source is picked below.\n"
         @"// #percent label=\"Pulse Amount\" group={\"Pulse\", \"metronome\"} "
         @"min=0 max=100 default=0\n"
         @"uniform float uPulseAmount;\n"
         @"\n"
         @"// #audio label=\"Pulse Audio\" gate=-50 release=0.18 smooth=0.07\n"
         @"uniform vec4 uPulseAudio[8];\n"
         @"\n"
         @"// How much each quarter of the spectrum drives it. One at 100% is "
         @"\"listen to\n"
         @"// that range\"; several open up a blend. Weights rather than a "
         @"picker so the\n"
         @"// ranges can overlap, and so they can be keyframed - a picker is "
         @"structural\n"
         @"// and can't animate.\n"
         @"// #multi label=\"Listen To\" group=\"Pulse\" fields={Bass,Low "
         @"Mid,High Mid,Treble} percent min=0 max=100 default=\"100,0,0,0\"\n"
         @"uniform vec4 uListenTo;\n"
         @"\n"
         @"// @osc Crop\n"
         @"//   primitive = box\n"
         @"//   binds     = uCrop\n"
         @"//   mid       = vec2(uCrop.z + uCrop.x * 0.5, 1.0 - uCrop.w - "
         @"uCrop.y * 0.5) + uPosition\n"
         @"//   half      = vec2(uCrop.x, uCrop.y) * 0.5 * uSize\n"
         @"//   toRect    = rect(mid - half, mid + half)\n"
         @"//   w         = rect.width / uSize\n"
         @"//   h         = rect.height / uSize\n"
         @"//   cx        = rect.min.x + rect.width * 0.5\n"
         @"//   cy        = rect.min.y + rect.height * 0.5\n"
         @"//   fromRect  = vec4(w, h, cx - uPosition.x - w * 0.5, 1.0 - cy + "
         @"uPosition.y - h * 0.5)\n"
         @"\n"
         @"// @osc Position\n"
         @"//   primitive = position\n"
         @"//   binds     = uPosition\n"
         @"//   mid       = vec2(uCrop.z + uCrop.x * 0.5, 1.0 - uCrop.w - "
         @"uCrop.y * 0.5)\n"
         @"//   toPos     = mid + uPosition\n"
         @"//   fromPos   = pos - mid\n"
         @"\n"
         @"// @osc Radius\n"
         @"//   primitive = point\n"
         @"//   binds     = uRadius\n"
         @"//   style     = hollow\n"
         @"//   cursor    = resize-diag\n"
         @"//   mid       = vec2(uCrop.z + uCrop.x * 0.5, 1.0 - uCrop.w - "
         @"uCrop.y * 0.5) + uPosition\n"
         @"//   half      = vec2(uCrop.x, uCrop.y) * 0.5 * uSize\n"
         @"//   corner    = mid + half\n"
         @"//   minH      = min(uCrop.x * uSize * aspect, uCrop.y * uSize)\n"
         @"//   power     = mix(5.0, 2.0, uRadius)\n"
         @"//   inset     = mix(1.0 - 1.0 / pow(2.0, 1.0 / power), 1.0 - 1.0 / "
         @"sqrt(2.0), uRadius)\n"
         @"//   corr      = 1.0 - 0.22 * sin(uRadius * pi)\n"
         @"//   pad       = minH * 0.05 + minH * 0.5 * uRadius * inset * corr\n"
         @"//   toPos     = corner - vec2(pad / aspect, pad)\n"
         @"\n"
         @"\n"
         @"// Peak level across a slice of the spectrum, given as fractions of "
         @"the whole.\n"
         @"// Slicing by fraction rather than by band index keeps \"Bass\" "
         @"meaning the same\n"
         @"// thing whatever band count the source reports. Constant loop "
         @"bound (the\n"
         @"// vec4[8] ceiling) with the range tested inside.\n"
         @"float bandPeak(float lo01, float hi01, int bands)\n"
         @"{\n"
         @"\tint lo = int(lo01 * float(bands));\n"
         @"\tint hi = max(lo, int(hi01 * float(bands)) - 1);\n"
         @"\tfloat lvl = 0.0;\n"
         @"\tfor (int i = 0; i < 32; i++)\n"
         @"\t{\n"
         @"\t\tif (i < lo || i > hi || i >= bands)\n"
         @"\t\t\tcontinue;\n"
         @"\t\tlvl = max(lvl, uPulseAudioBand(i)); // peak, so a transient "
         @"survives\n"
         @"\t}\n"
         @"\treturn lvl;\n"
         @"}\n"
         @"\n"
         @"\n"
         @"void mainImage(out vec4 O, in vec2 fc)\n"
         @"{\n"
         @"\tvec2 res = iResolution.xy;\n"
         @"\n"
         @"\tfloat sz = max(uSize, 0.001); // guard the divide below\n"
         @"\n"
         @"\t// The window straight from Crop (top-left origin, Y down), "
         @"scaled about its\n"
         @"\t// own centre by Size.\n"
         @"\tvec2 halfSize = uCrop.xy * res * 0.5 * sz;\n"
         @"\tvec2 winCentre = vec2(uCrop.z + uCrop.x * 0.5,\n"
         @"\t                      1.0 - uCrop.w - uCrop.y * 0.5) * res;\n"
         @"\n"
         @"\t// Position arrives in pixels, bottom-origin, so no scale and no "
         @"flip.\n"
         @"\tvec2 offset = uPosition;\n"
         @"\tvec2 centre = winCentre + offset;\n"
         @"\n"
         @"\tvec2 p = fc - centre; // window: Crop, Size and Position\n"
         @"\t// Content magnifies with the window: divide the offset from the "
         @"centre by\n"
         @"\t// Size so the same crop region fills the resized frame. At sz = "
         @"1 this is\n"
         @"\t// (fc - offset) / res, i.e. content sitting in place.\n"
         @"\tvec2 srcUV = (winCentre + (fc - centre) / sz) / res;\n"
         @"\tvec4 s = texture(iChannel0, srcUV);\n"
         @"\n"
         @"\tfloat r = uRadius * min(halfSize.x, halfSize.y); // stays "
         @"proportional\n"
         @"\tfloat d = roundedSDF(p, halfSize, r, uRadius);\n"
         @"\tfloat aa = max(fwidth(d), 1e-4);\n"
         @"\n"
         @"\t// Breath: 0 = bottom of the dip, 1 = full glow.\n"
         @"\t//\n"
         @"\t// `uPulseAudioBands` is a COMPILE-TIME constant (the declared "
         @"array size),\n"
         @"\t// not a count of whether a source is bound - so this can't tell "
         @"silence\n"
         @"\t// from nothing-connected, and with no audio every band reads 0 "
         @"and breath\n"
         @"\t// collapses to 0. Pulse Amount defaulting to 0 is what keeps "
         @"that from\n"
         @"\t// dimming the glow of a shader nobody wired audio into.\n"
         @"\tfloat breath = 1.0;\n"
         @"\tint bands = uPulseAudioBands;\n"
         @"\tif (uPulseAmount > 0.0 && bands > 0)\n"
         @"\t{\n"
         @"\t\t// Each range scaled by its own weight, then the loudest wins. "
         @"Max, not\n"
         @"\t\t// sum: two loud ranges shouldn't read louder than the loudest "
         @"one, and\n"
         @"\t\t// a single weight at 100% behaves exactly like picking that "
         @"range.\n"
         @"\t\tfloat lvl = 0.0;\n"
         @"\t\tlvl = max(lvl, bandPeak(0.00, 0.25, bands) * uListenTo.x);\n"
         @"\t\tlvl = max(lvl, bandPeak(0.25, 0.50, bands) * uListenTo.y);\n"
         @"\t\tlvl = max(lvl, bandPeak(0.50, 0.75, bands) * uListenTo.z);\n"
         @"\t\tlvl = max(lvl, bandPeak(0.75, 1.00, bands) * uListenTo.w);\n"
         @"\t\tbreath = clamp(lvl, 0.0, 1.0);\n"
         @"\t}\n"
         @"\t// Amount sets how far the breath dips; at 0 the glow never "
         @"varies.\n"
         @"\tfloat lo = 1.0 - uPulseAmount;\n"
         @"\tfloat pulseA = mix(lo, 1.0, breath);                // intensity\n"
         @"\tfloat pulseS = mix(mix(lo, 1.0, 0.5), 1.0, breath); // size, half "
         @"as deep\n"
         @"\n"
         @"\tfloat bw = uBorderWidth;\n"
         @"\tfloat gs = uGlowSize * pulseS;\n"
         @"\n"
         @"\t// Content silhouette, plus the border's outer silhouette (the "
         @"same shape\n"
         @"\t// grown by bw). Filling that outer shape UNDER the content "
         @"leaves a ring of\n"
         @"\t// exactly bw with correct corner joins, so there's no band "
         @"maths.\n"
         @"\tfloat shape = 1.0 - smoothstep(0.0, aa * 2.0, d);\n"
         @"\tfloat outer = 1.0 - smoothstep(0.0, aa * 2.0, d - bw);\n"
         @"\n"
         @"\t// Glow follows the outer edge, so a bordered frame casts the "
         @"shadow of its\n"
         @"\t// border rather than of the content inside it.\n"
         @"\t// The blurred silhouette IS the glow: its alpha is the falloff "
         @"and its\n"
         @"\t// colour is the pickup, so the two can't disagree. There's no "
         @"separate\n"
         @"\t// analytic falloff any more - that was a second curve fighting "
         @"the blur,\n"
         @"\t// and its plateau near the edge is what read as a solid border. "
         @"Offsetting\n"
         @"\t// samples the blur, which is how the drop shadow moves.\n"
         @"\tfloat gA = 0.0;\n"
         @"\tvec3 glowRGB = uGlowColor.rgb;\n"
         @"\tif (gs > 0.0 && uGlowColor.a > 0.0)\n"
         @"\t{\n"
         @"\t\tvec4 gb = texture(iChannel3, (fc - uGlowOffset * res) / res);\n"
         @"\t\t// The blurred alpha IS the glow profile: outside the shape it "
         @"runs from\n"
         @"\t\t// ~0.5 at the edge down to 0 at the blur's limit. Feather is a "
         @"gamma on\n"
         @"\t\t// it - low tightens to the shape, high spreads across the "
         @"whole blur.\n"
         @"\t\t//\n"
         @"\t\t// It used to be 1 - smoothstep(0, edge, 1 - gb.a), which "
         @"zeroed\n"
         @"\t\t// everything below 1 - edge: at the default feather that "
         @"killed every\n"
         @"\t\t// pixel under gb.a 0.3 outright and left the rest peaking at "
         @"0.14\n"
         @"\t\t// alpha. That's why there was no glow at any size - a wider "
         @"blur just\n"
         @"\t\t// spread a field that had already been multiplied to nothing.\n"
         @"\t\tfloat t = 1.0 - gb.a;\n"
         @"\t\tgA = pow(clamp(gb.a, 0.0, 1.0), mix(3.0, 0.5, uGlowFeather)) *\n"
         @"\t\t     uGlowColor.a * pulseA;\n"
         @"\t\tif (uGlowNoise > 0.0)\n"
         @"\t\t{\n"
         @"\t\t\t// Grain flowing outward in bands, so it reads as energy "
         @"leaving the\n"
         @"\t\t\t// edge rather than static sitting on top. It rides on how "
         @"far\n"
         @"\t\t\t// through the glow this pixel is, which the blurred alpha "
         @"already\n"
         @"\t\t\t// tells us.\n"
         @"\t\t\tvec2 cell = floor(fc / max(uNoiseScale, 1.0));\n"
         @"\t\t\tfloat rp = t * 6.0 - iTime * uNoiseSpeed;\n"
         @"\t\t\tfloat band = floor(rp);\n"
         @"\t\t\tfloat blend = smoothstep(0.0, 1.0, fract(rp));\n"
         @"\t\t\tfloat n = mix(frameHash(cell + band * vec2(127.1, 311.7)),\n"
         @"\t\t\t              frameHash(cell + (band + 1.0) * vec2(127.1, "
         @"311.7)),\n"
         @"\t\t\t              blend);\n"
         @"\t\t\tgA *= clamp(1.0 - uGlowNoise * (1.0 - n), 0.0, 1.0);\n"
         @"\t\t}\n"
         @"\t\t// Hold the picked-up colour as far out as the glow is still "
         @"visible.\n"
         @"\t\t// This used to fade at gb.a 0.02, but the ALPHA carries well "
         @"past that\n"
         @"\t\t// - at a high Feather pow(0.02, 0.5) is still ~0.14 - so the "
         @"colour\n"
         @"\t\t// reverted to flat while the glow was plainly there, and the "
         @"handover\n"
         @"\t\t// showed as a ring. The threshold only exists to keep the "
         @"divide off\n"
         @"\t\t// values too small to carry colour.\n"
         @"\t\tif (uGlowPickup > 0.0)\n"
         @"\t\t\tglowRGB = mix(glowRGB, gb.rgb / max(gb.a, 4e-4),\n"
         @"\t\t\t              uGlowPickup * smoothstep(1e-4, 4e-4, gb.a));\n"
         @"\t}\n"
         @"\n"
         @"\n"
         @"\t// Content, clipped to the source frame.\n"
         @"\tfloat cA = shape;\n"
         @"\tif (any(lessThan(srcUV, vec2(0.0))) || any(greaterThan(srcUV, "
         @"vec2(1.0))))\n"
         @"\t\tcA = 0.0;\n"
         @"\n"
         @"\tfloat bA = (bw > 0.0) ? outer * uBorderColor.a : 0.0;\n"
         @"\n"
         @"\t// Premultiplied \"over\", back to front: glow, border, content.\n"
         @"\tvec4 acc = vec4(glowRGB * gA, gA);\n"
         @"\tacc = vec4(uBorderColor.rgb * bA + acc.rgb * (1.0 - bA),\n"
         @"\t           bA + acc.a * (1.0 - bA));\n"
         @"\tacc = vec4(s.rgb * cA + acc.rgb * (1.0 - cA), cA + acc.a * (1.0 - "
         @"cA));\n"
         @"\n"
         @"\t// Bloom last, and ADDED rather than composited: scattered light "
         @"doesn't\n"
         @"\t// occlude what's under it. Buffer C's alpha is the blurred "
         @"brightness of\n"
         @"\t// the picture, so thresholding it here picks the regions that "
         @"are bright on\n"
         @"\t// average - steadier than thresholding per-pixel before the "
         @"blur, which\n"
         @"\t// makes small highlights flicker in and out as they cross the "
         @"cutoff.\n"
         @"\tif (uBloom > 0.0)\n"
         @"\t{\n"
         @"\t\tvec4 b = texture(iChannel3, fc / res);\n"
         @"\t\tvec3 bc = b.a > 0.003 ? b.rgb / b.a : vec3(0.0);\n"
         @"\t\tfloat thr = uBloomThreshold;\n"
         @"\t\tfloat lit = smoothstep(thr, min(thr + 0.2, 1.0),\n"
         @"\t\t                       max(bc.r, max(bc.g, bc.b)));\n"
         @"\t\tacc.rgb += bc * lit * uBloom * cA;\n"
         @"\t}\n"
         @"\n"
         @"\t// `acc` is built premultiplied, but the `// #alpha` output path "
         @"does\n"
         @"\t// kk_outColor = vec4(rgb * alpha, alpha) - it premultiplies for "
         @"us, so\n"
         @"\t// mainImage has to hand back STRAIGHT colour. Returning "
         @"premultiplied here\n"
         @"\t// multiplied by alpha twice.\n"
         @"\t//\n"
         @"\t// That only shows where alpha is PARTIAL. Content and border sit "
         @"at alpha\n"
         @"\t// 1, where squaring changes nothing, so they always looked "
         @"correct; the\n"
         @"\t// glow was the only partial-alpha part, and it alone got crushed "
         @"- a white\n"
         @"\t// glow at alpha 0.3 rendering as 0.09. The original shader never "
         @"caught it\n"
         @"\t// because its glow defaulted to BLACK, which survives any number "
         @"of\n"
         @"\t// multiplications unchanged.\n"
         @"\tO = (acc.a > 1e-4) ? vec4(acc.rgb / acc.a, acc.a) : vec4(0.0);\n"

         @"}\n";
}

// Shown when the user's shader fails to compile (e.g. uses iChannel textures or
// has a syntax error): animated dark-red hazard stripes, so a broken shader
// reads as clearly broken instead of a stale / blank frame.
NSString *MirageCustomErrorShaderSource(void) {
  return @"void mainImage( out vec4 fragColor, in vec2 fragCoord ) {\n"
         @"    vec2 uv = fragCoord / iResolution.xy;\n"
         @"    float s = step(0.5, fract((uv.x + uv.y) * 10.0 - iTime));\n"
         @"    vec3 col = mix(vec3(0.22,0.0,0.0), vec3(0.5,0.02,0.02), s);\n"
         @"    fragColor = vec4(col, 1.0);\n"
         @"}\n";
}
