#!/usr/bin/env python3
"""Build the changelog site (docs/) from Markdown release notes.

Source of truth:
  docs/changelog/plugins.json          metadata (name, kind, payhip)
  docs/changelog/<plugin>/<version>.md  one file per release (= a GitHub Release body)

Each release .md:
    <!-- date: 2026-05-24 -->         (invisible in GitHub; sets the date)
    ### New
    - A bullet, may use [links](https://...), **bold**, *italic*, `code`
    ### Fixed
    - Another bullet
    ![Caption](https://github.com/user-attachments/assets/UUID)   image or GIF
    https://github.com/user-attachments/assets/UUID              bare url on its own line = video

  Media: drag the file into the GitHub Release editor to get a user-attachments URL
  (GitHub-CDN hosted - keep media OUT of the repo). Use absolute urls so they render
  on GitHub and on the site.

Output (generated - do not hand-edit):
  docs/index.html, docs/<plugin>/index.html

Run:  python3 scripts/build-changelog.py
No dependencies (stdlib only).
"""

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
SRC = DOCS / "changelog"

GROUP_ORDER = ["New", "Improved", "Fixed"]
GROUP_CLASS = {"New": "feature", "Improved": "improvement", "Fixed": "fix"}
VIDEO_EXT = (".mp4", ".mov", ".webm", ".m4v")

# GitHub-style alerts: > [!CAUTION] etc. Render as colored callouts here AND on GitHub.
CALLOUT_LABEL = {
    "note": "Note",
    "tip": "Tip",
    "important": "Important",
    "warning": "Warning",
    "caution": "Caution",
}
CALLOUT_RE = re.compile(r"^>\s*\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*$", re.I)

GENERATED_NOTE = "<!-- generated by scripts/build-changelog.py - edit docs/changelog/*.md instead -->"

PAGE = """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{title}</title>
    <link rel="stylesheet" href="{css}" />
{head}  </head>
  <body>
    <main class="wrap">
{content}
    </main>
  </body>
</html>
"""


def esc(s):
    """Escape for text content (leave quotes/apostrophes literal)."""
    return html.escape(s, quote=False)


def inline_md(text):
    """Minimal inline Markdown -> HTML (escape first, then links/bold/italic/code)."""
    text = esc(text.strip())
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    return text


def version_key(v):
    base = v.split("-")[0]
    return tuple(int(p) if p.isdigit() else 0 for p in base.split("."))


def media_from(line):
    """A media line -> dict, or None. ![cap](url) = image/gif; bare URL line = video
    (matches GitHub drag-drop; user-attachment URLs have no extension)."""
    img = re.match(r"!\[([^\]]*)\]\(([^)]+)\)", line)
    if img:
        src = img.group(2).strip()
        return {"src": src, "caption": img.group(1).strip(), "video": src.lower().endswith(VIDEO_EXT)}
    if re.match(r"^https?://\S+$", line):
        return {"src": line, "caption": "", "video": True}
    return None


def parse_release(path):
    """Parse one release .md into {version, date, callouts, spotlight, groups}.

    Media placement is contextual:
      - before the first ### heading  -> spotlight (top of the release)
      - right after a bullet          -> attached under that bullet
    Callouts: GitHub alert blocks (> [!CAUTION] ...) -> release-level, rendered at top.
    """
    text = path.read_text(encoding="utf-8")
    version = path.stem
    m = re.search(r"<!--\s*date:\s*([^>]+?)\s*-->", text)
    date = m.group(1).strip() if m else ""

    callouts = []
    spotlight = []
    groups = {}  # name -> [ {text, media:[]} ]
    current = None
    bullet = None
    callout = None  # {type, body:[]} while collecting a > [!TYPE] block
    for raw in text.splitlines():
        line = raw.strip()
        if callout is not None:
            if line.startswith(">"):
                body = line[1:].strip()
                if body:
                    callout["body"].append(body)
                continue
            callouts.append(callout)
            callout = None
            # not a quote line -> fall through and process it normally
        if not line or line.startswith("<!--"):
            continue
        start = CALLOUT_RE.match(line)
        if start:
            callout = {"type": start.group(1).lower(), "body": []}
            continue
        med = media_from(line)
        if med:
            if bullet is not None:
                bullet["media"].append(med)
            else:
                spotlight.append(med)  # no bullet yet -> release-level spotlight
            continue
        if line.startswith("###"):
            current = line.lstrip("#").strip()
            groups.setdefault(current, [])
            bullet = None
            continue
        if line.startswith(("- ", "* ")):
            if current is None:
                current = "Changes"
                groups.setdefault(current, [])
            bullet = {"text": line[2:].strip(), "media": []}
            groups[current].append(bullet)
    if callout is not None:
        callouts.append(callout)
    return {
        "version": version,
        "date": date,
        "callouts": callouts,
        "spotlight": spotlight,
        "groups": groups,
    }


def load_plugin_releases(plugin_id):
    pdir = SRC / plugin_id
    if not pdir.is_dir():
        return []
    releases = [parse_release(p) for p in pdir.glob("*.md")]
    releases.sort(key=lambda r: version_key(r["version"]), reverse=True)
    return releases


def render_topbar(title, sub, href, logo):
    return (
        '      <header class="topbar">\n'
        '        <div class="brand">\n'
        f'          <img class="logo" src="{html.escape(logo)}" alt="" />\n'
        '          <div class="title">\n'
        f"            <h1>{esc(title)}</h1>\n"
        f'            <span class="sub">{esc(sub)}</span>\n'
        "          </div>\n"
        "        </div>\n"
        f'        <a class="cta" href="{html.escape(href)}">Get it on Payhip →</a>\n'
        "      </header>"
    )


def callout_html(c, indent=8):
    pad = " " * indent
    label = CALLOUT_LABEL.get(c["type"], c["type"].title())
    body = inline_md(" ".join(c["body"]).strip())
    return [
        f'{pad}<div class="callout {c["type"]}">',
        f'{pad}  <div class="callout-title">{esc(label)}</div>',
        f'{pad}  <div class="callout-body">{body}</div>',
        f"{pad}</div>",
    ]


def figure_html(m, indent, cls=""):
    pad = " " * indent
    open_tag = f'{pad}<figure class="{cls}">' if cls else f"{pad}<figure>"
    lines = [open_tag]
    if m["video"]:
        lines.append(f'{pad}  <video src="{html.escape(m["src"])}" controls playsinline></video>')
    else:
        lines.append(f'{pad}  <img src="{html.escape(m["src"])}" alt="{html.escape(m["caption"])}" />')
    if m["caption"]:
        lines.append(f'{pad}  <figcaption>{esc(m["caption"])}</figcaption>')
    lines.append(f"{pad}</figure>")
    return lines


def render_release(rel):
    out = ['      <section class="release">']
    out.append('        <div class="release-head">')
    out.append(f'          <h2>{esc(rel["version"])}</h2>')
    out.append(f'          <span class="date">{esc(rel["date"])}</span>')
    out.append("        </div>")

    for c in rel["callouts"]:
        out += callout_html(c)

    for m in rel["spotlight"]:
        out += figure_html(m, 8, cls="spotlight")

    names = [g for g in GROUP_ORDER if rel["groups"].get(g)]
    names += [g for g in rel["groups"] if g not in GROUP_ORDER and rel["groups"][g]]
    for name in names:
        cls = GROUP_CLASS.get(name, "kind")
        out.append('        <div class="group">')
        out.append(f'          <span class="tag {cls}">{esc(name)}</span>')
        out.append('          <ul class="bullets">')
        for item in rel["groups"][name]:
            if item["media"]:
                out.append(f'            <li>{inline_md(item["text"])}')
                for m in item["media"]:
                    out += figure_html(m, 14)
                out.append("            </li>")
            else:
                out.append(f'            <li>{inline_md(item["text"])}</li>')
        out.append("          </ul>")
        out.append("        </div>")
    out.append("      </section>")
    return "\n".join(out)


def write_page(path, title, css, content, version=None):
    # kk-version is the machine-readable version contract KKUpdateChecker reads -
    # so there is no separate manifest.json. The note + meta sit in <head>.
    base = css.rsplit("/", 1)[0] if "/" in css else "."  # assets dir (depth-relative)
    head = f"    {GENERATED_NOTE}\n"
    head += f'    <link rel="icon" type="image/png" sizes="32x32" href="{base}/favicon-32.png" />\n'
    head += f'    <link rel="icon" type="image/png" sizes="16x16" href="{base}/favicon-16.png" />\n'
    head += f'    <link rel="apple-touch-icon" href="{base}/apple-touch-icon.png" />\n'
    if version:
        head += f'    <meta name="kk-version" content="{html.escape(version)}" />\n'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        PAGE.format(title=title, css=css, head=head, content=content),
        encoding="utf-8",
    )


def build():
    meta = json.loads((SRC / "plugins.json").read_text(encoding="utf-8"))
    site_payhip = meta.get("payhip", "#")
    site_releases = meta.get("releases", "")
    plugins = meta.get("plugins", {})

    # plugin pages
    for pid, info in plugins.items():
        releases = load_plugin_releases(pid)
        latest = releases[0]["version"] if releases else None
        payhip = info.get("payhip", site_payhip)
        parts = [render_topbar(info["name"], "What's New", payhip, "../assets/apple-touch-icon.png")]
        parts += [render_release(r) for r in releases]
        if releases:
            oldest = releases[-1]["version"]
            rel_url = info.get("releases", site_releases)
            tail = (
                f'Earlier releases are <a href="{html.escape(rel_url)}">on GitHub</a>.'
                if rel_url
                else "Earlier releases are on GitHub."
            )
            parts.append(
                '      <div class="changelog-start">\n'
                f"        Changelog begins at {esc(oldest)}. {tail}\n"
                "      </div>"
            )
        parts.append(
            '      <footer class="foot">\n'
            f'        {esc(info["name"])} is a Final Cut Pro {esc(info["kind"])}, '
            'part of the <a href="../">Keyframeless suite</a>.\n'
            "      </footer>"
        )
        write_page(
            DOCS / pid / "index.html",
            f'{info["name"]} - What\'s New',
            "../assets/style.css",
            "\n".join(parts),
            version=latest,
        )
        print(f"  {pid}: {len(releases)} release(s) (latest {latest})")

    # root index
    rows = [render_topbar(meta.get("siteTitle", "Keyframeless"), "Release notes", site_payhip, "assets/apple-touch-icon.png")]
    rows.append('      <ul class="entries">')
    for pid, info in plugins.items():
        kind = "Extension" if "extension" in info["kind"].lower() else "Plugin"
        rows.append("        <li>")
        rows.append(f'          <span class="tag kind">{kind}</span>')
        rows.append(
            f'          <span><a href="{pid}/">{esc(info["name"])} - What\'s New</a></span>'
        )
        rows.append("        </li>")
    rows.append("      </ul>")
    rows.append(
        '      <footer class="foot">\n'
        "        Changelogs for the Keyframeless suite for Final Cut Pro.\n"
        "      </footer>"
    )
    write_page(DOCS / "index.html", "Keyframeless - Release notes", "assets/style.css", "\n".join(rows))
    print("  index: done")


if __name__ == "__main__":
    if not (SRC / "plugins.json").exists():
        sys.exit(f"missing {SRC / 'plugins.json'}")
    build()
