/*
 * SPDX-FileCopyrightText: 2026 overpolish
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 */

#pragma once

// Plain-text lane/value-space description handed to the AI values-pass.
// Extracted from Plugin+CustomUI.m so the (long) prose lives on its own. See
// the original comment below.
#import <Foundation/Foundation.h>

static inline NSString *MeshAILaneSchemaText(void) {
  return @"Lane labels and value spaces. This is a procedural generator with "
         @"twelve "
         @"styles selected by \"Type\": Mesh (animated colour spots blended "
         @"into "
         @"a soft gradient), Dithering (a procedural shape rendered through "
         @"a "
         @"dither into two colours), Grainy (a procedural shape field "
         @"indexing a multi-colour ramp with a grainy overlay), Warp "
         @"(colour fields warped by noise + swirl over a base pattern), "
         @"Neuro (a glowing web of fluid lines), Simplex (a multi-colour "
         @"gradient mapped through Simplex noise into stepped bands), and "
         @"Metaballs (gooey coloured balls roaming the centre and merging "
         @"into organic blobs), God Rays (animated rays of light "
         @"radiating from the centre with a central glow), Fluid (a "
         @"molten, "
         @"marbled flow from an iterative domain warp), Wisp (glowing "
         @"neon tendril wisps drifting over a dark backdrop), Silk "
         @"(flowing draped silk fabric with anisotropic sheen), and Strata "
         @"(stacked geological layers with folded boundaries). Set "
         @"the lanes for the chosen type.\n\n"
         @"- \"Type\": the generator style. A structural choice (NOT "
         @"animated), "
         @"stored as an index: 0 = Mesh, 1 = Dithering, 2 = Grainy, 3 = Warp, "
         @"4 = Neuro, 5 = Simplex, 6 = Metaballs, 7 = God Rays, 8 = Fluid, "
         @"9 = Wisp, 10 = Silk, 11 = Strata. Default 0.\n"
         @"- \"Speed\": single value, 0..3 multiplier of the animation rate "
         @"(1 = normal, 0 = frozen, 2 = twice as fast). Shared by all types. "
         @"Animatable. Default 1.\n"
         @"- \"Seed\": integer, the animation start-frame / layout variation "
         @"(any value). Shared by all types. NOT animatable. Default 0.\n"
         @"- \"Origin\": two components [X, Y] normalised 0..1 (0.5,0.5 = "
         @"centre, Y up). Shifts the pattern within the frame. Shared by all "
         @"types. Default [0.5, 0.5].\n"
         @"- \"Scale\": percent zoom of the pattern, 100 = 1x (slider caps at "
         @"400, field allows more). Shared by all types. Default 100.\n"
         @"- \"Rotation\": degrees 0..360, rotates the pattern. Shared by all "
         @"types. Default 0.\n"
         @"- \"Grain\": percent 0..100. Core film-grain overlay, shared by all "
         @"types (subtle default also removes 8-bit banding; higher = "
         @"stylistic "
         @"grain). Default 6.\n"
         @"- \"Grain Size\": grain cell size in whole pixels (higher = "
         @"coarser). "
         @"Shared by all types. Default 2.\n"
         @"\nMesh (Type 0):\n"
         @"- \"Distortion\": percent 0..100. Organic noise warp of the field "
         @"(0 = calm, higher = more churning folds). Default 80.\n"
         @"- \"Swirl\": percent 0..100. Vortex twist around the centre. "
         @"Default 10.\n"
         @"- \"Color 1\", \"Color 2\", ... : the gradient's colour spots, each "
         @"[r, g, b, a] in sRGB 0..1. Positions are procedural, so only the "
         @"colours are set. Set as many as the user asks for.\n"
         @"\nDithering (Type 1):\n"
         @"- \"Shape\": the procedural pattern. Structural choice (NOT "
         @"animated), index: 0 = Simplex, 1 = Warp, 2 = Dots, 3 = Wave, "
         @"4 = Ripple, 5 = Swirl. Default 0.\n"
         @"- \"Dither\": the dither matrix. Structural choice, index: "
         @"0 = Random, 1 = 2x2, 2 = 4x4, 3 = 8x8 (higher = finer/smoother). "
         @"Default 3.\n"
         @"- \"Pixel Size\": the dither grid cell size in pixels, integer "
         @"1..20 "
         @"(higher = chunkier). Default 2.\n"
         @"- \"Background\": the base colour [r, g, b, a] in sRGB 0..1.\n"
         @"- \"Foreground\": the ink colour [r, g, b, a] in sRGB 0..1.\n"
         @"\nGrainy (Type 2):\n"
         @"- \"Pattern\": the procedural shape field. Structural choice (NOT "
         @"animated), index: 0 = Wave, 1 = Dots, 2 = Truchet, 3 = Corners, "
         @"4 = Ripple, 5 = Blob. Default 0.\n"
         @"- \"Softness\": percent 0..100. Colour-band edge smoothness "
         @"(0 = hard steps, 100 = smooth gradient). Default 90.\n"
         @"- \"Intensity\": percent 0..100. Noise distortion between the "
         @"colour "
         @"bands. Default 40.\n"
         @"- \"Noise\": percent 0..100. Grainy overlay amount. Default 25.\n"
         @"- \"Color 1\", \"Color 2\", ... : the ramp colours (shared with "
         @"Mesh), each [r, g, b, a] in sRGB 0..1. Set as many as the user "
         @"asks for (up to 7 used).\n"
         @"- \"Background\": the base colour [r, g, b, a] in sRGB 0..1 "
         @"(shared with Dithering).\n"
         @"\nWarp (Type 3):\n"
         @"- \"Base\": the base pattern under the warp. Structural choice (NOT "
         @"animated), index: 0 = Checks, 1 = Stripes, 2 = Edge. Default 0.\n"
         @"- \"Proportion\": percent 0..100. Blend point between colours "
         @"(50 = equal distribution). Default 50.\n"
         @"- \"Softness\": percent 0..100. Colour-transition sharpness "
         @"(0 = hard edge, 100 = smooth). Shared with Grainy. Default 90.\n"
         @"- \"Shape Scale\": percent 0..100. Zoom of the base pattern. "
         @"Default 50.\n"
         @"- \"Distortion\": percent 0..100. Noise distortion strength. Shared "
         @"with Mesh. Default 80.\n"
         @"- \"Swirl\": percent 0..100. Swirl distortion strength. Shared with "
         @"Mesh. Default 10.\n"
         @"- \"Swirl Iterations\": integer 0..20, layered swirl passes "
         @"(effective with Swirl > 0). Default 8.\n"
         @"- \"Color 1\", \"Color 2\", ... : the warped colours (shared with "
         @"Mesh), each [r, g, b, a] in sRGB 0..1. Up to 10 used.\n"
         @"\nNeuro (Type 4):\n"
         @"- \"Brightness\": percent 0..100. Luminosity of the glowing "
         @"crossing "
         @"points. Default 20.\n"
         @"- \"Contrast\": percent 0..100. Sharpness of the bright-dark "
         @"transition. Default 30.\n"
         @"- \"Foreground\": the highlight colour [r, g, b, a] in sRGB 0..1 "
         @"(shared with Dithering).\n"
         @"- \"Mid\": the main line colour [r, g, b, a] in sRGB 0..1.\n"
         @"- \"Background\": the base colour [r, g, b, a] in sRGB 0..1 "
         @"(shared with Dithering + Grainy).\n"
         @"\nSimplex (Type 5):\n"
         @"- \"Steps\": integer 1..10, extra colour bands between the base "
         @"colours (1 = smooth, higher = more stepped). Default 1.\n"
         @"- \"Softness\": percent 0..100. Band-edge sharpness (0 = hard, "
         @"100 = smooth). Shared with Grainy / Warp. Default 90.\n"
         @"- \"Color 1\", \"Color 2\", ... : the gradient colours (shared with "
         @"Mesh), each [r, g, b, a] in sRGB 0..1. Up to 10 used.\n"
         @"\nMetaballs (Type 6):\n"
         @"- \"Count\": integer 1..20, the number of gooey balls. Animatable. "
         @"Default 6.\n"
         @"- \"Size\": percent 0..100, the ball size (higher = larger, more "
         @"merging). Default 100.\n"
         @"- \"Color 1\", \"Color 2\", ... : the ball colours (shared with "
         @"Mesh), each [r, g, b, a] in sRGB 0..1. Cycled across the balls.\n"
         @"- \"Background\": the base colour [r, g, b, a] in sRGB 0..1 "
         @"(shared with Dithering + Grainy + Neuro).\n"
         @"\nGod Rays (Type 7):\n"
         @"- \"Density\": percent 0..100. The number of rays (higher = more, "
         @"finer rays). Default 6.\n"
         @"- \"Spots\": percent 0..100. Ray length (higher = shorter, spottier "
         @"rays). Default 1.\n"
         @"- \"Glow Size\": percent 0..100. Size of the central glow. "
         @"Default 22.\n"
         @"- \"Glow\": percent 0..100. Brightness of the central glow. "
         @"Default 28.\n"
         @"- \"Rays\": percent 0..100. Ray visibility / strength. Default 20.\n"
         @"- \"Bloom\": percent 0..100. Blend of the rays from alpha (0) to "
         @"additive/glowing (100), also mixing in the bloom overlay colour. "
         @"Default 1.5.\n"
         @"- \"Color 1\", \"Color 2\", ... : the ray colours (shared with "
         @"Mesh), each [r, g, b, a] in sRGB 0..1. Up to 5 used.\n"
         @"- \"Bloom Color\": the overlay colour blended with the rays "
         @"[r, g, b, a] in sRGB 0..1.\n"
         @"- \"Background\": the base colour [r, g, b, a] in sRGB 0..1 "
         @"(shared with Dithering + Grainy + Neuro).\n"
         @"\nFluid (Type 8):\n"
         @"- \"Marble\": percent 0..300. Domain-warp strength (0 = smooth soft "
         @"blobs, 100 = default, higher = intense folded marbling). Default "
         @"100.\n"
         @"- \"Detail\": percent 0..100. Fbm persistence (how much fine, "
         @"high-frequency marbling survives; higher = busier). Default 48.\n"
         @"- \"Vibrance\": percent 0..200. Colour-layer separation (low = "
         @"muted / base-dominant, high = punchy). Default 100.\n"
         @"- \"Color 1\", \"Color 2\", ... : the flow colours (shared with "
         @"Mesh), each [r, g, b, a] in sRGB 0..1. Composited in layers "
         @"(1 = base, then mid, then bright, then a glow tint). Up to 4 "
         @"used.\n"
         @"\nWisp (Type 9):\n"
         @"- \"Wisps\": percent 0..200. Tendril-wisp coverage / strength "
         @"(higher = more, brighter strands). Default 100.\n"
         @"- \"Strands\": percent 0..250. Wisp fineness (higher = finer, more "
         @"numerous strands). Default 100.\n"
         @"- \"Radiance\": percent 0..300. HDR neon gain / bloom punch. "
         @"Default 100.\n"
         @"- \"Color 1\", \"Color 2\", ... : the neon ramp (shared with Mesh), "
         @"each [r, g, b, a] in sRGB 0..1, ordered outer glow -> surface -> "
         @"inner -> hot core. Up to 4 used.\n"
         @"- \"Background\": the dark backdrop [r, g, b, a] in sRGB 0..1 "
         @"(shared with Dithering + Grainy + Neuro).\n"
         @"\nSilk (Type 10):\n"
         @"- \"Sheen\": percent 0..200. Silk specular / sheen intensity (the "
         @"sharp anisotropic highlight streaks). Default 100.\n"
         @"- \"Folds\": percent 0..300. Fold density (higher = more, finer "
         @"fabric folds). Default 50.\n"
         @"- \"Drape\": percent 0..200. Domain-warp strength (how much the "
         @"folds curve and flow). Default 100.\n"
         @"- \"Color 1\", \"Color 2\", \"Color 3\": the three fabric-layer "
         @"hues (shared with Mesh), each [r, g, b, a] in sRGB 0..1 (back to "
         @"front). Each layer's dark/mid/bright/sheen tones derive from its "
         @"hue. 3 used.\n"
         @"- \"Background\": the dark backdrop [r, g, b, a] in sRGB 0..1 "
         @"(shared with Dithering + Grainy + Neuro).\n"
         @"\nStrata (Type 11):\n"
         @"- \"Layers\": integer 2..24, the number of geological strata bands. "
         @"Animatable. Default 16.\n"
         @"- \"Tectonics\": percent 0..250. Deformation strength (how much the "
         @"strata fold, warp and buckle). Default 100.\n"
         @"- \"Texture\": percent 0..200. Washi-paper grain intensity. "
         @"Default 100.\n"
         @"- \"Color 1\", \"Color 2\", ... : the strata colours (shared with "
         @"Mesh), each [r, g, b, a] in sRGB 0..1. Each layer hashes to one of "
         @"these swatches. Add more for more variety.\n";
}
