/*
 * SPDX-FileCopyrightText: 2026 overpolish
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 */

#pragma once

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT double KeyframelessKitVersionNumber; //! Version number
FOUNDATION_EXPORT const unsigned char
    KeyframelessKitVersionString[]; //! Version string

#import <KeyframelessKit/KKAlertStackView.h>
#import <KeyframelessKit/KKAlertView.h>
#import <KeyframelessKit/KKAnchorMiniController.h>
#import <KeyframelessKit/KKAnchorOSC.h>
#import <KeyframelessKit/KKArcOSC.h>
#import <KeyframelessKit/KKBezierPath.h>
#import <KeyframelessKit/KKBoxOSC.h>
#import <KeyframelessKit/KKBoxOSCSet.h>
#import <KeyframelessKit/KKCheckboxRowView.h>
#import <KeyframelessKit/KKCheckboxView.h>
#import <KeyframelessKit/KKChevronView.h>
#import <KeyframelessKit/KKColor.h>
#import <KeyframelessKit/KKColorLanes.h>
#import <KeyframelessKit/KKColorWellView.h>
#import <KeyframelessKit/KKConstants.h>
#import <KeyframelessKit/KKCropModel.h>
#import <KeyframelessKit/KKCropOSC.h>
#import <KeyframelessKit/KKCustomGroupHeaderView.h>
#import <KeyframelessKit/KKDataBlob.h>
#import <KeyframelessKit/KKEasing.h>
#import <KeyframelessKit/KKFieldEditorSupport.h>
#import <KeyframelessKit/KKGapPopoverTypes.h>
#import <KeyframelessKit/KKGradientBarView.h>
#import <KeyframelessKit/KKGradientControl.h>
#import <KeyframelessKit/KKGradientFavorites.h>
#import <KeyframelessKit/KKGradientFavoritesPopover.h>
#import <KeyframelessKit/KKGradientSampling.h>
#import <KeyframelessKit/KKHelpSection.h>
#import <KeyframelessKit/KKHelpView.h>
#import <KeyframelessKit/KKHostInfo.h>
#import <KeyframelessKit/KKIconButtonOSC.h>
#import <KeyframelessKit/KKJoyrideController.h>
#import <KeyframelessKit/KKJoyrideDragStep.h>
#import <KeyframelessKit/KKJoyrideGuideHost.h>
#import <KeyframelessKit/KKJoyrideLanesBinder.h>
#import <KeyframelessKit/KKJoyrideOSCSegment.h>
#import <KeyframelessKit/KKJoyrideTrigger.h>
#import <KeyframelessKit/KKKbd.h>
#import <KeyframelessKit/KKLabelView.h>
#import <KeyframelessKit/KKLaneRowView.h>
#import <KeyframelessKit/KKLog.h>
#import <KeyframelessKit/KKMarkup.h>
#import <KeyframelessKit/KKMetalDeviceCache.h>
#import <KeyframelessKit/KKMiniViewerCropEditor.h>
#import <KeyframelessKit/KKMiniViewerFeed.h>
#import <KeyframelessKit/KKMiniViewerGuide.h>
#import <KeyframelessKit/KKMiniViewerGuideScroll.h>
#import <KeyframelessKit/KKMiniViewerRenderer.h>
#import <KeyframelessKit/KKMiniViewerView.h>
#import <KeyframelessKit/KKMotionBlur.h>
#import <KeyframelessKit/KKMotionBlurReconstruct.h>
#import <KeyframelessKit/KKMotionLean.h>
#import <KeyframelessKit/KKOSCGuide.h>
#import <KeyframelessKit/KKOSCGuideBridge.h>
#import <KeyframelessKit/KKOSCGuideStrategy.h>
#import <KeyframelessKit/KKOSCLabel.h>
#import <KeyframelessKit/KKOSCShaderTypes.h>
#import <KeyframelessKit/KKOnScreenControl+CoordinateSpace.h>
#import <KeyframelessKit/KKPaddedScrollView.h>
#import <KeyframelessKit/KKPaletteGenerator.h>
#import <KeyframelessKit/KKParameterRowView.h>
#import <KeyframelessKit/KKPathBoolean.h>
#import <KeyframelessKit/KKPathMorph.h>
#import <KeyframelessKit/KKPillToggleRowView.h>
#import <KeyframelessKit/KKPlayheadPoller.h>
#import <KeyframelessKit/KKPlugin+Color.h>
#import <KeyframelessKit/KKPlugin+Crop.h>
#import <KeyframelessKit/KKPlugin+InspectorCallbacks.h>
#import <KeyframelessKit/KKPlugin+MiniViewerFeed.h>
#import <KeyframelessKit/KKPlugin+OSCVisibility.h>
#import <KeyframelessKit/KKPlugin.h>
#import <KeyframelessKit/KKPluginHost.h>
#import <KeyframelessKit/KKPluginInstanceState.h>
#import <KeyframelessKit/KKPointOSC.h>
#import <KeyframelessKit/KKPointOSCSet.h>
#import <KeyframelessKit/KKPointRowView.h>
#import <KeyframelessKit/KKPopoverExtraRow.h>
#import <KeyframelessKit/KKPopoverKeepAlive.h>
#import <KeyframelessKit/KKPopupSelectView.h>
#import <KeyframelessKit/KKPositionMiniController.h>
#import <KeyframelessKit/KKPositionOSC.h>
#import <KeyframelessKit/KKPresets.h>
#import <KeyframelessKit/KKRadialOSCSet.h>
#import <KeyframelessKit/KKRandomRowView.h>
#import <KeyframelessKit/KKRectBorderOSC.h>
#import <KeyframelessKit/KKRenderPrimitives.h>
#import <KeyframelessKit/KKResizeCursor.h>
#import <KeyframelessKit/KKRingOSC.h>
#import <KeyframelessKit/KKRingOSCSet.h>
#import <KeyframelessKit/KKRotationOSC.h>
#import <KeyframelessKit/KKRotationOSCMath.h>
#import <KeyframelessKit/KKRotationOSCSet.h>
#import <KeyframelessKit/KKSVGParser.h>
#import <KeyframelessKit/KKScaleGizmo.h>
#import <KeyframelessKit/KKScaleMiniController.h>
#import <KeyframelessKit/KKScaleOSC.h>
#import <KeyframelessKit/KKSeedView.h>
#import <KeyframelessKit/KKSegmentEditView+Guide.h>
#import <KeyframelessKit/KKSegmentEditView.h>
#import <KeyframelessKit/KKSeparatorView.h>
#import <KeyframelessKit/KKShaderTypes.h>
#import <KeyframelessKit/KKShape.h>
#import <KeyframelessKit/KKSliderRowView.h>
#import <KeyframelessKit/KKSnapEngine.h>
#import <KeyframelessKit/KKSpatialCurve.h>
#import <KeyframelessKit/KKSpectrogram.h>
#import <KeyframelessKit/KKSquarePointOSC.h>
#import <KeyframelessKit/KKTimelineAIMerge.h>
#import <KeyframelessKit/KKTimelineAdvancedView.h>
#import <KeyframelessKit/KKTimelineBasicView+Guide.h>
#import <KeyframelessKit/KKTimelineBasicView.h>
#import <KeyframelessKit/KKTimelineInspectorButtons.h>
#import <KeyframelessKit/KKTimelineInspectorView+Guide.h>
#import <KeyframelessKit/KKTimelineInspectorView.h>
#import <KeyframelessKit/KKTimelineLanesView+Guide.h>
#import <KeyframelessKit/KKTimelineLanesView.h>
#import <KeyframelessKit/KKTimingCompat.h>
#import <KeyframelessKit/KKTimingEvaluation.h>
#import <KeyframelessKit/KKTimingGuide.h>
#import <KeyframelessKit/KKTimingLane.h>
#import <KeyframelessKit/KKTimingStage.h>
#import <KeyframelessKit/KKTokens.h>
#import <KeyframelessKit/KKToolbar.h>
#import <KeyframelessKit/KKUpdateChecker.h>
#import <KeyframelessKit/NSColor+KKColors.h>
